### PR TITLE
Avoid ClassCastException on direct SDK access

### LINKED ISSUE #336: ClassCastException when using opentelemetry SDK with auto agent
I am experimenting the OT auto agent with OT SDK. My use case is rather simple:

- A simple java job that triggers some HTTP client calls to some services
- Since my java job itself would not be instrumented by the auto-agent, I added dependency to opentelemetry-sdk to start the scope and span
- Since the http client calls are made within the scope, they should get picked up by the auto agent

However, in the beginning of the code, when I tried to obtain the tracer from SDK
```
public static void main(String[] args) throws InterruptedException {
        // Get the tracer
        TracerSdkProvider tracerProvider = OpenTelemetrySdk.getTracerProvider();
...
```

Exception is triggered : 
```
Exception in thread "main" java.lang.ClassCastException: class io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider cannot be cast to class io.opentelemetry.sdk.trace.TracerSdkProvider (io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider and io.opentelemetry.sdk.trace.TracerSdkProvider are in unnamed module of loader 'app')
```

I am wondering if my usage is legit as in #10 ? Or have I misused the auto agent/sdk? 

Many thanks in advance!

### PR DESCRIPTION
**Pull request by trask**
Closes #336

### CODE REVIEW

File: instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java [hunk 1]
```diff
@@ -42,4 +53,20 @@ public Tracer get(final String instrumentationName, final String instrumentation
...
         contextStore);
   }
+
+  // this is called by OpenTelemetrySdk, which expects to get back a real TracerProviderSdk
+  @Override
+  public Object unobfuscate() {
+    if (!messageAlreadyLogged.getAndSet(true)) {
+      String message =
+          "direct usage of the OpenTelemetry SDK is not supported when running agent"
+              + " (run with debug logging to see stack trace)";
```
Comment (anuraaga) [inline instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java:63]: I'd include the flag here if mentioning debug logging

File: instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java [hunk 2]
```diff
@@ -42,4 +53,20 @@ public Tracer get(final String instrumentationName, final String instrumentation
             .get(instrumentationName, instrumentationVersion),
         contextStore);
   }
+
+  // this is called by OpenTelemetrySdk, which expects to get back a real TracerProviderSdk
+  @Override
+  public Object unobfuscate() {
+    if (!messageAlreadyLogged.getAndSet(true)) {
+      String message =
+          "direct usage of the OpenTelemetry SDK is not supported when running agent"
```
Comment (anuraaga) [inline instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java:62]: Adding the concrete operation can provide good context

Direct usage of the OpenTelemetry SDK by calling OpenTelemetrySdk.getTracrProvider() is not...

Comment (anuraaga) [reply instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java:62]: Also maybe a link to how to configure the agent (presumably what they were trying to do).

**Comment by iNikem** [comment]
These shaded and unshaded terms are very confusing to me and don't seem natural. Can we replace them with some words that reflect the problem domain, not the solution space? 

I mean we have one set of classes that we bring as dependency, right? And another set which application can bring, right? So maybe agent/application or internal/external or something?

**Comment by anuraaga** [comment]
Yeah I think we can address it outside this PR but I agree with @iNikem. Actually, it seems to be the worst of all worlds right now, where unprefixed is shaded, and prefixed is unshaded which is highly unusual. So use-case specific package names like @iNikem suggests would be nice, if there's a technical problem with that, I think swapping so unprefixed is unshaded would be easier to make presentations about :P

**Comment by trask** [comment]
> Can we replace them with some words that reflect the problem domain, not the solution space?

Great idea, created #935

File: instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java [hunk 3]
```diff
@@ -42,4 +53,20 @@ public Tracer get(final String instrumentationName, final String instrumentation
...
+              + " (run with debug logging to see stack trace)";
+      if (log.isDebugEnabled()) {
+        log.debug(message, new Exception("stack trace"));
+      } else {
+        log.info(message);
+      }
+    }
+    return ((Obfuscated<?>) originalTracerProvider).unobfuscate();
```
Comment (iNikem) [inline instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java:70]: Sorry, but I am totally confused. Javadoc for `Obfuscated` says: "because auto-instrumentation takes over the static global providers returned by the API and points them to it's embedded SDK". And also "Static global providers are obfuscated when they are returned from the API to prevent users from casting them to their SDK specific implementation."

But it seems to me that here we are doing exactly the same, no? We don't "take over the static global providers returned by the API and point them to it's embedded SDK", but we take global provider, unobfuskcate it and return to the end users.

Can we have a chat where @trask we explain to me (and @anuraaga if he wishes so) this whole business with obfuscation, shading, future support for multiple versions of API/SDK etc etc. Because I am totally confused.

**Comment by iNikem** [comment]
A! I was too late! :(

**Comment by trask** [comment]
Oh my bad!! I meant to address @anuraaga's comments. Will submit another PR and we can continue discussing there.

**Comment by iNikem** [comment]
Can we discuss this during special meeting?

**Comment by trask** [comment]
👍 added special topic meeting to public calendar for Tue Aug 11, 10pm Pacific Time

https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFjajExYW5xdmtsdTRpM2dzZWNqajM0YWEgZ29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBn&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com

File: instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (trask) [reply instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/auto/instrumentation/opentelemetryapi/trace/UnshadedTracerProvider.java:62]: Not supported means that if you use `OpenTelemetrySdk.getTraceProvider()`, you won't get back the agent's `TraceProvider` bridge, and so any telemetry you emit won't get intercepted / correlated / exported by the agent the way we do if you use `OpenTelemetry.getTraceProvider()` from OpenTelemetry API
