### PR TITLE
compatible different command line style for find jar path 

### LINKED ISSUE #12545: compatible different command line style for find jar path
### Describe the bug

compatible command like : java -jar -XX:MaxRAM=128m app.jar
The JAR file name does not always come immediately after the -jar command; there may be other JVM parameters in between the two.

by now, if we use the java -jar -XX:MaxRAM=128m app.jar command to start the applicaion. we can not get the real jar name.
we will get the warn log like below:
otel.javaagent 2024-10-29 09:24:19:600 +0000] [main] WARN io.opentelemetry.instrumentation.resources.ManifestResourceProvider - Error reading manifest java.nio.file.NoSuchFileException: -XX:MaxRAM=128m

### Steps to reproduce

start application by  java -jar -XX:MaxRAM=128m app.jar

### Expected behavior

get the real jar name

### Actual behavior

can not get jar name

### Javaagent or library instrumentation version

latest

### Environment

**JDK**: 17
**OS**: redhatLinux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by misaya98**
compatible command like : **java -jar -XX:MaxRAM=128m app.jar**
The JAR file name does not always come immediately after the **-jar** command; there may be other JVM parameters in between the two.

by now, if we use the java -jar -XX:MaxRAM=128m app.jar command to start the applicaion. we can not get the real jar name.
we will get the warn log like below:
`
otel.javaagent 2024-10-29 09:24:19:600 +0000] [main] WARN io.opentelemetry.instrumentation.resources.ManifestResourceProvider - Error reading manifest java.nio.file.NoSuchFileException: -XX:MaxRAM=128m
`

Resolves #12545

### CODE REVIEW

**Review by trask — COMMENTED** [review]
can you add a test for this to `JarServiceNameDetectorTest`?

**Comment by misaya98** [comment]
> can you add a test for this to `JarServiceNameDetectorTest`?

yes.

File: instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java [hunk 1]
```diff
@@ -90,6 +105,11 @@ static String[] getArgs(String jarName) {
     return new String[] {"-Dtest=42", "-Xmx666m", "-jar", path, "abc", "def"};
   }
 
+  static String[] getArgs_jar_command_variant(String jarName) {
+    String path = Paths.get("path", "to", "app", jarName).toString();
+    return new String[] {"-Dtest=42", "-jar", "-Xmx666m", path, "abc", "def"};
```
Comment (trask) [inline instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java:110]: 😈

```suggestion
    return new String[] {"-Dtest=42", "-jar", "-Xmx512m", path, "abc", "def"};
```

**Review by trask — APPROVED** [review]

File: instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java [hunk 2]
```diff
@@ -90,6 +105,11 @@ static String[] getArgs(String jarName) {
     return new String[] {"-Dtest=42", "-Xmx666m", "-jar", path, "abc", "def"};
   }
 
+  static String[] getArgs_jar_command_variant(String jarName) {
+    String path = Paths.get("path", "to", "app", jarName).toString();
+    return new String[] {"-Dtest=42", "-jar", "-Xmx512m", path, "abc", "def"};
+  }
```
Comment (laurit) [inline instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java:111]: this is used in only one test, you can inline it in the test

File: instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java [hunk 3]
```diff
@@ -73,6 +73,21 @@ void createResource_processHandleJar() {
         .containsEntry(ServiceAttributes.SERVICE_NAME, "my-service");
   }
 
+  @Test
+  void createResource_processHandleJar_jar_command_variant() {
```
Comment (laurit) [inline instrumentation/resources/library/src/test/java/io/opentelemetry/instrumentation/resources/JarServiceNameDetectorTest.java:77]: We rarely use `_` in method names and if we do then usually we only use one. Could you rename the test method to `createResource_processHandleJarExtraFlag`

File: instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/MainJarPathFinder.java [hunk 4]
```diff
@@ -44,9 +44,13 @@ Path detectJarPath() {
...
     String[] javaArgs = getProcessHandleArguments.get();
-    for (int i = 0; i < javaArgs.length; ++i) {
-      if ("-jar".equals(javaArgs[i]) && (i < javaArgs.length - 1)) {
-        return Paths.get(javaArgs[i + 1]);
+    boolean jarOptionFound = false;
+    for (String javaArg : javaArgs) {
+      if ("-jar".equals(javaArg)) {
+        jarOptionFound = true;
+      }
+      if (jarOptionFound && !javaArg.startsWith("-")) {
```
Comment (laurit) [inline instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/MainJarPathFinder.java:52]: perhaps use `else if`. There should also be a comment describing why this is done. Something along the line of `// flags can appear between -jar and the jar path, ignore them`

Comment (misaya98) [reply instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/MainJarPathFinder.java]: thanks for your suggestion.

**Review by laurit — APPROVED** [review]
