### PR TITLE
Make sure muzzle build-time check actually validates anything

### LINKED ISSUE #2110: Investigate muzzle builds not failing when they should on GHA
**Describe the bug**
Sometimes muzzle tasks on GHA succeed even though they should not - and when you run the same muzzle task locally it fails (as expected).

See: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2094#issuecomment-765569295, https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2094#issuecomment-765671043

**What did you expect to see?**
Muzzle tasks on GHA should behave same as locally (i.e. fail when they are expected to fail).

### PR DESCRIPTION
**Pull request by iNikem**
Fixes #2110

### CODE REVIEW

**Comment by trask** [comment]
🤯 really looking forward to hearing the next chapter of this story (I do hope it's not too scary).

File: buildSrc/src/main/groovy/MuzzlePlugin.groovy [hunk 1]
```diff
@@ -95,10 +95,7 @@ class MuzzlePlugin implements Plugin<Project> {
     project.tasks.compileMuzzle.dependsOn(bootstrapProject.tasks.compileJava)
     project.tasks.compileMuzzle.dependsOn(toolingProject.tasks.compileJava)
     project.afterEvaluate {
-      project.tasks.compileMuzzle.dependsOn(project.tasks.compileJava)
-      if (project.tasks.getNames().contains('compileScala')) {
-        project.tasks.compileMuzzle.dependsOn(project.tasks.compileScala)
-      }
+      project.tasks.compileMuzzle.dependsOn(project.tasks.classes)
```
Comment (mateuszrzeszutek) [inline buildSrc/src/main/groovy/MuzzlePlugin.groovy:98]: This seems to be the actual fix of our muzzle problems - what does it change? We still use `compileJava` two lines above, is that OK?

File: instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle [hunk 2]
```diff
@@ -1,7 +1,9 @@
-apply from: "$rootDir/gradle/instrumentation.gradle"
+apply from: "$rootDir/gradle/instrumentation-library.gradle"
 
 def scalaVersion = '2.12'
 
 dependencies {
+  compileOnly project(':javaagent-api')
+  compileOnly project(':javaagent-tooling')
```
Comment (mateuszrzeszutek) [inline instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle:7]: Hmm, it's not really a "piece of library instrumentation" if it depends on javaagent artifacts... I wonder if we need another "module type" like `javaagent-shared` for those modules. (In another issue/PR though)

File: gradle/instrumentation.gradle [hunk 3]
```diff
@@ -20,6 +19,11 @@ apply from: "$rootDir/gradle/instrumentation-common.gradle"
 
 if (projectDir.name == 'javaagent') {
   archivesBaseName = projectDir.parentFile.name
+
+  //This is a special project that has only ComponentInstaller but not InstrumentationModule
+  if (archivesBaseName != 'runtime-metrics') {
```
[the remark this answers is not in the document]
Comment (iNikem) [reply gradle/instrumentation.gradle:24]: I have thought about that. Currently if there is no muzzle directive we verify against JDK classes. I don't know if we actually need that. @trask ?

File: instrumentation/rxjava-2.0/javaagent/rxjava-2.0-javaagent.gradle [hunk 4]
```diff
@@ -4,7 +4,9 @@ muzzle {
   pass {
     group = "io.reactivex.rxjava2"
     module = "rxjava"
-    versions = "[2.0.0,)"
+    versions = "[2.0.6,)"
+    extraDependency "io.reactivex.rxjava2:rxjava:2.0.6"
```
[the remark this answers is not in the document]
Comment (iNikem) [reply instrumentation/rxjava-2.0/javaagent/rxjava-2.0-javaagent.gradle:8]: this module does not depend on this jar. `library` module does. This is the same case as with aws-sdk. We should change MuzzlePlugin to be able to handle such situation automatically, but currently it does not.

File: buildSrc/src/main/groovy/MuzzlePlugin.groovy (hunk 1 above)
Comment (iNikem) [reply buildSrc/src/main/groovy/MuzzlePlugin.groovy:98]: Yes, toolingProject and bootstrapProject are Ok to use `compileJava`, although we may want to change that to `classes` as well for consistency. The problem is that in instrumentation modules we use a separate bytebuddy compilation plugin. And that plugin messes with `compileJava` task. Using `classes` instead guarantees that byte buddy ran as well.

File: instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle (hunk 2 above)
Comment (iNikem) [reply instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle:7]: Yeah, I am not happy about this as well, but don't have any better solution that does not explode the scope.

File: gradle/instrumentation.gradle (hunk 3 above)
[the remark this answers is not in the document]
Comment (mateuszrzeszutek) [reply gradle/instrumentation.gradle:24]: Hmm, we do have a separate directive syntax for JDK:

```groovy
muzzle {
  pass {
    coreJdk()
  }
}
```

File: instrumentation/rxjava-2.0/javaagent/rxjava-2.0-javaagent.gradle (hunk 4 above)
[the remark this answers is not in the document]
Comment (mateuszrzeszutek) [reply instrumentation/rxjava-2.0/javaagent/rxjava-2.0-javaagent.gradle:8]: Maybe this will be fixed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2554 once it's implemented

File: buildSrc/src/main/groovy/MuzzlePlugin.groovy (hunk 1 above)
Comment (mateuszrzeszutek) [reply buildSrc/src/main/groovy/MuzzlePlugin.groovy:98]: Can you add a comment about that? That was kind of non-obvious fix

File: gradle/instrumentation.gradle (hunk 3 above)
[the remark this answers is not in the document]
Comment (anuraaga) [reply gradle/instrumentation.gradle:24]: Agree that we shouldn't run muzzle if nothing is declared if it's simple to implement.

File: instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle (hunk 2 above)
Comment (anuraaga) [reply instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle:7]: It look like the common -> library pattern worked out ok for most artifacts. For this one how about same hack as runtime metrics?

File: buildSrc/src/main/groovy/MuzzlePlugin.groovy (hunk 1 above)
Comment (iNikem) [reply buildSrc/src/main/groovy/MuzzlePlugin.groovy:98]: I simplified and unified this.

File: instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle (hunk 2 above)
Comment (iNikem) [reply instrumentation/play-ws/play-ws-common/library/play-ws-common-library.gradle:7]: Got back to javaagent

**Review by mateuszrzeszutek — APPROVED** [review]

File: gradle/java.gradle [hunk 5]
```diff
@@ -94,6 +94,7 @@ jar {
 repositories {
   mavenCentral()
   mavenLocal()
+  jcenter()
```
Comment (trask) [inline gradle/java.gradle:97]: is this change intentional?

File: instrumentation/elasticsearch/elasticsearch-rest-common/library/elasticsearch-rest-common-library.gradle [hunk 6]
```diff
@@ -0,0 +1,6 @@
+apply from: "$rootDir/gradle/instrumentation-library.gradle"
+
+dependencies {
+  compileOnly project(':javaagent-api')
```
Comment (trask) [inline instrumentation/elasticsearch/elasticsearch-rest-common/library/elasticsearch-rest-common-library.gradle:4]: this doesn't look like it's needed
```suggestion
```

File: instrumentation/elasticsearch/elasticsearch-transport-common/library/elasticsearch-transport-common-library.gradle [hunk 7]
```diff
@@ -0,0 +1,6 @@
+apply from: "$rootDir/gradle/instrumentation-library.gradle"
+
+dependencies {
+  compileOnly project(':javaagent-api')
```
Comment (trask) [inline instrumentation/elasticsearch/elasticsearch-transport-common/library/elasticsearch-transport-common-library.gradle:4]: same
```suggestion
```

File: instrumentation/hibernate/hibernate-common/library/hibernate-common-library.gradle [hunk 8]
```diff
@@ -0,0 +1,9 @@
+/*
+ * Classes that are common to all versions of the Hibernate instrumentation.
+ */
+
+apply from: "$rootDir/gradle/instrumentation-library.gradle"
+
+dependencies {
+  compileOnly project(':javaagent-api')
```
Comment (trask) [inline instrumentation/hibernate/hibernate-common/library/hibernate-common-library.gradle:8]: since this needs `javaagent-api`, does it make sense to keep this module as `hibernate-common-javaagent`?

File: instrumentation/rocketmq-client-4.8/javaagent/rocketmq-client-4.8-javaagent.gradle [hunk 9]
```diff
@@ -4,7 +4,7 @@ muzzle {
   pass {
     group = "org.apache.rocketmq"
     module = 'rocketmq-client'
-    versions = "[4.8.0,)"
+    versions = "[4.0.0,)"
```
Comment (trask) [inline instrumentation/rocketmq-client-4.8/javaagent/rocketmq-client-4.8-javaagent.gradle:7]: @addname if tests pass against 4.0, let's run tests against that version and rename the module to `rocketmq-client-4.0`

File: instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java [hunk 10]
```diff
@@ -18,6 +19,7 @@
 import net.bytebuddy.description.type.TypeDescription;
 import net.bytebuddy.matcher.ElementMatcher;
 
+@AutoService(InstrumentationModule.class)
```
Comment (trask) [inline instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java:22]: um, how were tests passing? 😟

File: instrumentation/jaxws/jaxws-common/library/jaxws-common-library.gradle [hunk 11]
```diff
@@ -0,0 +1,5 @@
+apply from: "$rootDir/gradle/instrumentation-library.gradle"
+
+dependencies {
+  compileOnly project(':javaagent-api')
+}
```
Comment (trask) [inline instrumentation/jaxws/jaxws-common/library/jaxws-common-library.gradle:5]: doesn't look needed
```suggestion
```

File: instrumentation/play-ws/play-ws-common/javaagent/play-ws-common-javaagent.gradle [hunk 12]
```diff
@@ -3,5 +3,7 @@ apply from: "$rootDir/gradle/instrumentation.gradle"
 def scalaVersion = '2.12'
 
 dependencies {
+  compileOnly project(':javaagent-api')
+  compileOnly project(':javaagent-tooling')
```
Comment (trask) [inline instrumentation/play-ws/play-ws-common/javaagent/play-ws-common-javaagent.gradle:7]: looks unused after switching back to `-javaagent`
```suggestion
```

**Review by trask — COMMENTED** [review]
since you updated muzzle to ignore modules that don't have a muzzle directive, should we move the `-common-library` modules back to `-common-javaagent`? seems a little confusing to have `-library` modules (which will show up under the maven groupId with other library modules) for instrumentation that does not really have library instrumentation

File: instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle [hunk 13]
```diff
@@ -5,7 +5,7 @@ muzzle {
     group = "org.grails"
     module = "grails-web-url-mappings"
     versions = "[3.0,)"
-    skipVersions += ['3.1.15']
+    skipVersions += ['3.1.15', '3.3.6']
```
Comment (trask) [inline instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle:8]: I saw a recent build fail on `3.3.6` too, but I don't see it in the maven central metadata: https://repo1.maven.org/maven2/org/grails/grails-web-url-mappings/maven-metadata.xml, and I can't reproduce it locally..

Comment (trask) [reply instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle:8]: I pushed this `skipVersions` line to #2611 and will merge there to unblock a couple of PRs that look stuck on this too

**Comment by trask** [comment]
(fyi I merged main into your branch to resolve the merge conflict I created)

File: instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle (hunk 13 above)
Comment (iNikem) [reply instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle]: Grails module has a separate repository, `https://repo.grails.org/grails/core`. It does have `3.3.6` but that has a SNAPSHOT transitive dependency which we fail to retrieve.

Comment (trask) [reply instrumentation/grails-3.0/javaagent/grails-3.0-javaagent.gradle]: oh I totally missed that, thx (I just needed to read down a few lines 😭)

File: gradle/java.gradle (hunk 5 above)
Comment (iNikem) [reply gradle/java.gradle:97]: No, removed.

File: instrumentation/hibernate/hibernate-common/library/hibernate-common-library.gradle (hunk 8 above)
Comment (iNikem) [reply instrumentation/hibernate/hibernate-common/library/hibernate-common-library.gradle]: Moved back

**Review by mateuszrzeszutek — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]

File: instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java (hunk 10 above)
Comment (trask) [reply instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java:22]: ah, looks like rxjava2 javaagent tests just need the executor instrumentation to pass, I guess that's not too surprising

Comment (iNikem) [reply instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java:22]: It should be. This means that test is not sensitive and thus useless :(

Comment (trask) [reply instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java:22]: cc: @piotr-sumo when you have time can you see if there's a test we can add for rxjava2 that doesn't pass purely due to executor instrumentation?

Comment (anuraaga) [reply instrumentation/rxjava-2.0/javaagent/src/main/java/io/opentelemetry/instrumentation/rxjava2/RxJava2InstrumentationModule.java:22]: This is being addressed in #2672

File: instrumentation/rocketmq-client-4.8/javaagent/rocketmq-client-4.8-javaagent.gradle (hunk 9 above)
Comment (trask) [reply instrumentation/rocketmq-client-4.8/javaagent/rocketmq-client-4.8-javaagent.gradle:7]: nevermind, i took a quick look and tests didn't compile against earlier versions, not a problem to keep as-is
