### PR TITLE
document & test jmx metric implicit aggregation

### LINKED ISSUE #14070: Add ability to drop JMX MBean attributes and aggregate properly
With JMX Insights, we have the ability to capture JMX metrics using a simple YAML configuration file.

As found while working on #14067 , some JMX MBeans have some technical details leak into their object names, which forces to capture extra "technical metric attributes" that are not relevant for the metric consumer.

MBeans are published in a tree-like structure with optional key/value pairs, the metric values are extracted from their MBean attributes.

JMX metrics are extracted from those using one or more _MBean query_ that can have wildcards for those key/value pairs

For example, with the Jetty application server, when we need to capture the "select count" metric:
- `org.eclipse.jetty.io:context=*,type=managedselector,id=*` MBean query allows to get all the MBean instances providing the `selectCount` MBean attribute
- by default 10 instances of such MBean exist, each with a distinct value of `id` key.
- the current JMX implementation will attempt to capture all of those as 10 distinct metrics with the same identity unless we map the `id` key value as a metric attribute, hence producing 10 distinct metrics.
- we need to provide the aggregate sum of `selectCount` attribute over all those instances and capture it as a single metric
- in this particular case, in addition the `context` key also needs to be discarded because there is often a single transient value (thus potentially high-cardinality over time).

Here is how it looks like with VisualVM:

Image

The `context` key value is equal to `HTTP_1_1@524d6d96`, and the `id` key have 10 distinct values from `0` to `9`.

Having the ability to discard some metrics attributes and perform relevant aggregation seems to be possible through the usage of [metric views](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#view), so I think we should be able to leverage this feature and apply it for JMX metrics.

For the distinct values of `id` having those as metric attributes is not relevant for the metric consumer.

For the `context` key, we can consider this as an exception (but one we have to get by) as it goes against the [recommendations for MBean names](https://www.oracle.com/java/technologies/javase/management-extensions-best-practices.html), in particular for this statement:

> The name of the same object should not change between different executions of the application, so for example it should not contain items like a "JVM id" or the "MBean Server Id" that will change with each execution

### PR DESCRIPTION
**Pull request by SylvainJuge**
Fixes #14070

After further investigation, aggregation of values over multiple MBean instances already works as expected, this PR adds proper test and documentation.

This however confirms that using this aggregation with `gauge` metrics can produce unpredictable results when more than one MBean instance as the "last value" aggregation is being used. Tests and documentation have been updated to reflect this.

### CODE REVIEW

**Comment by trask** [comment]
cc @PeterF778 @robsunday

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java [hunk 1]
```diff
@@ -0,0 +1,274 @@
...
+    sdk =
+        OpenTelemetrySdk.builder()
+            .setMeterProvider(SdkMeterProvider.builder().registerMetricReader(reader).build())
+            .build();
+  }
+
+  @AfterEach
+  void after() throws Exception {
+    ObjectName objectName =
+        new ObjectName("otel.jmx.test:type=" + Hello.class.getSimpleName() + ",*");
```
Comment (robsunday) [inline instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: Optional: could be `new ObjectName(DOMAIN + ":type=" + Hello.class.getSimpleName() + ",*");`

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java [hunk 2]
```diff
@@ -0,0 +1,274 @@
...
+  private static ObjectName getObjectName(@Nullable String a, @Nullable String b) {
+    StringBuilder parts = new StringBuilder();
+    parts.append("otel.jmx.test:type=").append(Hello.class.getSimpleName());
+    if (a != null) {
+      parts.append(",a=").append(a);
+    }
+    if (b != null) {
+      parts.append(",b=").append(b);
+    }
+    try {
```
Comment (robsunday) [inline instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: No need for this `try/catch` because all calling test methods already declare `throws Exception`

Comment (SylvainJuge) [reply instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/14111/commits/5d86086be0c4fac155ef7a8d5cdc0af18af9bb3c

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java (hunk 1 above)
Comment (SylvainJuge) [reply instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/14111/commits/5d86086be0c4fac155ef7a8d5cdc0af18af9bb3c

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+
+  @AfterAll
+  static void tearDown() {
+    MBeanServerFactory.releaseMBeanServer(theServer);
+  }
+
+  @BeforeEach
+  void before() {
+    reader = InMemoryMetricReader.createDelta();
+    sdk =
```
Comment (laurit) [inline instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: any reason you couldn't use
```java
  @RegisterExtension
  static final InstrumentationExtension testing = LibraryInstrumentationExtension.create();
```
and `testing.waitAndAssertMetrics()`?

Comment (SylvainJuge) [reply instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: I wasn't aware of this, I'll try to use that instead.

Comment (SylvainJuge) [reply instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: done in 29b2b0933a0fd9335c047c0159d12e47436c38de

**Comment by PeterF778** [comment]
Just thinking about aggregating `gauge` metrics. Would it make sense to _average_ the values? This would solve the issue with non-deterministic aggregation of multiple values, and it would work as expected when only one value is subject to aggregation.

**Comment by SylvainJuge** [comment]
> Just thinking about aggregating `gauge` metrics. Would it make sense to _average_ the values? This would solve the issue with non-deterministic aggregation of multiple values, and it would work as expected when only one value is subject to aggregation.

While this would bring some determinism, I think it would still provide unexpected results depending on which metric is being captured:
- for a metric that measures an average: the result is an average of an average
- for a metric that measures a maximum: the result would be an average of two maximums

If we apply this to the context of web/application containers, one hypothetical web server could be to have two connectors, each monitored with its own MBean instance: for example one configured for http traffic and one for https. In practice most of the traffic would happen only on one of those configured connectors, which means the metrics from the other one would be zero. In such case the metrics reported would be half of the actual and expected value.

However, doing so could help to provide a "consistently less wrong value", as in example we could have either the correct expected value or a zero.

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java [hunk 4]
```diff
@@ -0,0 +1,246 @@
...
+                    metricAssert.hasLongSumSatisfying(sum -> sum.hasPointsSatisfying(pointAsserts));
+                  }
+                }));
+  }
+
+  private static void startTestMetric(
+      String metricName, String mbean, List<MetricAttribute> attributes, MetricInfo.Type metricType)
+      throws MalformedObjectNameException {
+    JmxMetricInsight metricInsight =
+        JmxMetricInsight.createService(testing.getOpenTelemetrySdk(), 0);
```
Comment (laurit) [inline instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: I'd use
```suggestion
        JmxMetricInsight.createService(testing.getOpenTelemetry(), 0);
```
since `JmxMetricInsight` doesn't need the`OpenTelemetrySdk`

**Review by laurit — APPROVED** [review]

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java [hunk 5]
```diff
@@ -0,0 +1,245 @@
...
+    } else {
+      waitAndAssertMetric(
+          metricName,
+          metricType,
+          point -> point.hasValue(4).hasAttribute(metricAttribute, "x"),
+          point -> point.hasValue(6).hasAttribute(metricAttribute, "y"));
+    }
+  }
+
+  private static final AtomicInteger metricCounter = new AtomicInteger(0);
```
Comment (robsunday) [inline instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: [minor] I'd move this declaration to the top of the class

**Review by robsunday — APPROVED** [review]

File: instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java (hunk 5 above)
Comment (SylvainJuge) [reply instrumentation/jmx-metrics/library/src/test/java/io/opentelemetry/instrumentation/jmx/engine/MetricAggregationTest.java]: Fixed in c9152c9ece
