### PR TITLE
Do not set the http.route attribute in JSF instrumentations by default

### LINKED ISSUE #5753: http_server_duration_bucket generates high cardinality metrics
**Describe the bug**
The Java agent, when configured to export metrics with Prometheus exporter, creates as expected the bucket `http_server_duration_bucket`.

This metric also has the `http_route` label, which produces high cardinality because it contains full paths like:
```
http_server_duration_bucket{container="xxx", endpoint="xxx", http_flavor="1.1", http_host="xxx", http_method="GET", http_route="/app/wsrest/userlogo/holding.png", http_scheme="http", http_status_code="200", instance="xxx:9464", job="xxx", le="7500.0", namespace="wms", pod="xxxx", service="wms"}
```
In my cluster this caused the number of time series to increase of ~300k !

**Steps to reproduce**
1. Instrument a Java app to export metrics with Prometheus exporter
2. Setup a Prometheus instance to scrape those metrics
3. Query Prometheus for http_server_duration_bucket

**What did you expect to see?**
http_server_duration_bucket should export lower cardinality metrics

**What did you see instead?**
http_server_duration_bucket export high cardinality metrics

**What version are you using?**
1.12.1

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: Ubuntu 20.04
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
..., but still override the server span name.

Resolves #5753

### CODE REVIEW

**Review by trask — APPROVED** [review]

File: instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/config/ExperimentalConfig.java [hunk 1]
```diff
@@ -38,6 +38,11 @@ public boolean viewTelemetryEnabled() {
         "otel.instrumentation.common.experimental.view-telemetry.enabled", !suppressViewSpans);
   }
 
+  public boolean useViewNameAsHttpRoute() {
+    return config.getBoolean(
+        "otel.instrumentation.common.experimental.view-name-as-http-route.enabled", false);
+  }
```
Comment (trask) [inline instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/config/ExperimentalConfig.java:44]: do you have a need for this? if not, I'm always in favor of only adding config options on demand 😄

Comment (mateuszrzeszutek) [reply instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/config/ExperimentalConfig.java:44]: No, I don't, I added it "just to be on the safe side" 😂 

Let's drop it 👍
