### PR TITLE
Fix Quarkus correlation

### LINKED ISSUE #2493: Quarkus Netty broken traces on Kubernetes
**Describe the bug**
 I am working on integrating Open Telemetry to an existing microservices architecture with nested libraries such as Kafka, couchbase, netty.  There are some problems with tracing data. For one HTTP request, netty creates separated two traces. I think that is a context pass problem. 

**What did you expect to see?**
For one request one trace.

**What did you see instead?**
For one request two separate traces.

**What version are you using?**
  Opentelemetry agent version `v0.17.0`

**Environment**
OS: Linux 4.4.0-197 
Container platform: Kubernetes
Java version: 1.8.0_265-b01

**Additional context**
alt text
alt text 
alt text

### PR DESCRIPTION
**Pull request by trask**
Correlation was getting lost between netty/vertx (request) and quarkus/jax-rs (controller).

The fix is one line (I will highlight it with a review comment).

The PR also adds a smoke test image for Quarkus and a (currently ignored) smoke test.

Will send follow-up PR once smoke test image is published to enable the test.

Resolved #2493

### CODE REVIEW

File: instrumentation/executors/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/javaconcurrent/AbstractExecutorInstrumentation.java [hunk 1]
```diff
@@ -88,10 +88,10 @@ protected AbstractExecutorInstrumentation() {
         "java.util.concurrent.ScheduledThreadPoolExecutor",
         "java.util.concurrent.ThreadPoolExecutor",
         "org.apache.tomcat.util.threads.ThreadPoolExecutor",
-        "org.eclipse.jetty.util.thread.QueuedThreadPool", // dispatch() is covered in the jetty
-        // module
+        "org.eclipse.jetty.util.thread.QueuedThreadPool", // dispatch() covered in the jetty module
         "org.eclipse.jetty.util.thread.ReservedThreadExecutor",
         "org.glassfish.grizzly.threadpool.GrizzlyExecutorService",
+        "org.jboss.threads.EnhancedQueueExecutor",
```
Comment (trask) [inline instrumentation/executors/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/javaconcurrent/AbstractExecutorInstrumentation.java:94]: this line is the fix

File: smoke-tests/images/grpc/settings.gradle [hunk 2]
```diff
@@ -1,10 +1 @@
-/*
- * This file was generated by the Gradle 'init' task.
- *
- * The settings file is used to specify which projects to include in your build.
- *
- * Detailed information about configuring a multi-project build in Gradle can be found
- * in the user manual at https://docs.gradle.org/6.6/userguide/multi_project_builds.html
- */
-
```
Comment (trask) [inline smoke-tests/images/grpc/settings.gradle:9]: removed this to match the other smoke test `settings.gradle` files

File: smoke-tests/src/test/groovy/io/opentelemetry/smoketest/QuarkusSmokeTest.groovy [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    startTarget(jdk)
+
+    def currentAgentVersion = new JarFile(agentPath).getManifest().getMainAttributes().get(Attributes.Name.IMPLEMENTATION_VERSION)
+
+    when:
+    client().get("/hello").aggregate().join()
+    Collection<ExportTraceServiceRequest> traces = waitForTraces()
+
+    then:
+    countSpansByName(traces, '/hello') == 1
```
Comment (trask) [inline smoke-tests/src/test/groovy/io/opentelemetry/smoketest/QuarkusSmokeTest.groovy:40]: without the fix, the SERVER span name is `/` b/c the correlation is lost between the SERVER span and the JAX-RS routing instrumentation, so the SERVER span name cannot be updated

**Review by anuraaga — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]
