### PR TITLE
Fix sporadically failing smoke test

### LINKED ISSUE #3890: Nightly build
<a href="https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/1152901418">
Nightly build #68</a> failed. Please take a look and fix it ASAP.

### PR DESCRIPTION
**Pull request by trask**
Closes #3890

### CODE REVIEW

File: smoke-tests/src/test/java/io/opentelemetry/smoketest/windows/WindowsTestContainerManager.java [hunk 1]
```diff
@@ -314,6 +314,8 @@ private Container startContainer(
 
     CreateContainerCmd createCommand = client.createContainerCmd(imageName);
     createAction.accept(createCommand);
+    // default appears to be 1gb which is not enough for liberty
+    createCommand.getHostConfig().withMemory(2_000_000_000L);
```
Comment (laurit) [inline smoke-tests/src/test/java/io/opentelemetry/smoketest/windows/WindowsTestContainerManager.java:318]: Is the problem that jvm ergonomics isn't able to figure out that it is running inside container and picks way too large heap size? Maybe we should add something like `-Xmx512m` or less in `AbstractTestContainerManager.getAgentEnvironment` where we also add `-javaagent`

Comment (trask) [reply smoke-tests/src/test/java/io/opentelemetry/smoketest/windows/WindowsTestContainerManager.java]: good call

`java -XX:+PrintFlagsFinal -version | grep -w MaxHeapSize`

* linux container with 1g memory limit: `268,435,456`
* linux container with "default gha" memory limit: `1,824,522,240`
* windows container with 1g memory limit: `1,879,048,192`
* windows container with "default gha" memory limit: `1,879,048,192`

https://github.com/trask/test-jvm-container-ergonomics/actions/runs/1156983349

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Reminds me of when I had to run a Java binary proxy on Java 9 in a container and hating it (ergonomics are backported from Java 10)
