### PR TITLE
Fix ByteBuddy tasks failing on daemon reuse.

### LINKED ISSUE #1674: Can't run `byteBuddyJava` task twice without stopping Gradle daemon
```
 ./gradlew :instrumentation:jetty-8.0:bytebuddyjava --no-build-cache --stacktrace --rerun-tasks
 ./gradlew :instrumentation:jetty-8.0:bytebuddyjava --no-build-cache --stacktrace --rerun-tasks
```

fails with

```
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Error reading class io.opentelemetry.javaagent.instrumentation.servlet.v3_0.TagSettingAsyncListener
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.visitEnd(MuzzleCodeGenerator.java:458)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitEnd(TypeWriter.java:5140)
        at net.bytebuddy.utility.visitor.MetadataAwareClassVisitor.visitEnd(MetadataAwareClassVisitor.java:370)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:715)
        at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:394)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3892)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
        at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:252)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4498)
        at net.bytebuddy.build.Plugin$Engine$Default$Preprocessor$Resolved.call(Plugin.java:4455)
        at net.bytebuddy.build.Plugin$Engine$Dispatcher$ForSerialTransformation.accept(Plugin.java:3538)
        at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4302)
        at net.bytebuddy.build.gradle.AbstractByteBuddyTask.doApply(AbstractByteBuddyTask.java:331)
        ... 99 more
Caused by: java.lang.IllegalStateException: Error reading class io.opentelemetry.javaagent.instrumentation.servlet.v3_0.TagSettingAsyncListener
        at io.opentelemetry.javaagent.tooling.muzzle.collector.ReferenceCollector.collectReferencesFrom(ReferenceCollector.java:101)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.generateReferences(MuzzleCodeGenerator.java:144)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.MuzzleCodeGenerator$GenerateMuzzleReferenceMatcherMethodAndField.visitEnd(MuzzleCodeGenerator.java:207)
        ... 111 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at net.bytebuddy.jar.asm.ClassReader.readStream(ClassReader.java:309)
        at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:277)
        at io.opentelemetry.javaagent.tooling.muzzle.collector.ReferenceCollector.collectReferencesFrom(ReferenceCollector.java:83)
        ... 113 more
```

If I do `./gradlew --stop` and run the task, it succeeds, then run again and fails - `./gradlew --stop` always brings it back to a working state for one attempt until the next time the daemon is stopped.

### PR DESCRIPTION
**Pull request by agoallikmaa**
Fixes #1674. The issue was caused by a global `JarFile` cache in the JDK which caches `JarFile` instances with path as key globally with no regard to file modification times. This caused the same instance to be used across several builds in the daemon, which breaks when the file is rebuilt in between two invocations of the same task. The fix is to disable the use of cache when loading class file streams in `ReferenceCollector`.

### CODE REVIEW

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/collector/ReferenceCollector.java [hunk 1]
```diff
@@ -91,6 +85,24 @@ public void collectReferencesFrom(String adviceClassName) {
...
+                    .getResource(Utils.getResourceName(className)),
+                "Couldn't find class file %s",
+                className)
+            .openConnection();
+
+    // Since the JarFile cache is not per class loader, but global with path as key, using cache may
+    // cause the same instance of JarFile being used for consecutive builds, even if the file has
+    // been changed. There is still another cache in ZipFile.Source which checks last modified time
+    // as well, so the zip index is not scanned again on every class.
+    connection.setUseCaches(false);
```
Comment (anuraaga) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/collector/ReferenceCollector.java:102]: Magic!

**Review by anuraaga — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/collector/ReferenceCollector.java (hunk 1 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/collector/ReferenceCollector.java:102]: 🤯

**Review by mateuszrzeszutek — APPROVED** [review]
