### PR TITLE
Only reset server context if there is a leak.

### LINKED ISSUE #2853: gRPC instrumentation breaks ProtoReflectionService
**Describe the bug**
When running with otel agent 1.1.0 and grpc instrumentation the `ProtoReflectionService` (https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java) fails with a NPE.

**Steps to reproduce**
- Run a grpc server with `ProtoReflecitonService` and otel-agent 1.1.0
- call the reflection endpoint. For example, `grpcurl --plaintext host:port list`

**What did you expect to see?**
The service to function

**What did you see instead?**
NPE on grpc server 

> java.lang.NullPointerException: null
	at io.grpc.protobuf.services.ProtoReflectionService.getRefreshedIndex(ProtoReflectionService.java:93)
	at io.grpc.protobuf.services.ProtoReflectionService.serverReflectionInfo(ProtoReflectionService.java:134)
	at io.grpc.reflection.v1alpha.ServerReflectionGrpc$MethodHandlers.invoke(ServerReflectionGrpc.java:220)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler.startCall(ServerCalls.java:228)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.Contexts.interceptCall(Contexts.java:52)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_5.TracingServerInterceptor.interceptCall(TracingServerInterceptor.java:58)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:648)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:626)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:416)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:557)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:532)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**What version are you using?**
otel-agent 1.1.0
grpc 1.34.1

**Environment**
Compiler: AdoptOpenJDK 11.0.9
OS: debian buster

**Additional context**
It looks like the NPE may be due to 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/grpc-1.5/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_5/internal/ContextStorageBridge.java

In particular 
`grpc.io.Context$Key.get(Context)` checks `context.keyValueEntries` and it only has `otel-context` in it, not the expected key `io.grpc.Server.SERVER_CONTEXT_KEY`

### PR DESCRIPTION
**Pull request by anuraaga**
Resetting to root was always a hack that we accepted out of necessity for leaking instrumentations. But we reached the end of the line :) Context is a shared resource and who knows what's been added to it before we get a chance to create a span, resetting it arbitrarily isn't really allowed. This new version is still not ideal but at least improves the situation a bit.

Fixes #2853

### CODE REVIEW

File: instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/BaseTracer.java [hunk 1]
```diff
@@ -298,10 +298,19 @@ protected Throwable unwrapThrowable(Throwable throwable) {
...
+    if (Span.fromContextOrNull(parent) != null) {
+      // A span has leaked from another thread.
+      // We want either span context extracted from the carrier or invalid one.
+      // We DO NOT want any span context potentially lingering in the current context.
+      // We reset to the root context, which may not always be appropriate (e.g., a framework added
+      // an item to the context before we create a span) but it is safer than removing all the
+      // possible spans that instrumentation may have added and such frameworks as of now do not
+      // have leaks.
+      parent = Context.root();
+    }
```
Comment (mateuszrzeszutek) [inline instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/BaseTracer.java:311]: Should we add the same logic to `ServerInstrumenter`?

**Review by mateuszrzeszutek — APPROVED** [review]

File: instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/BaseTracer.java (hunk 1 above)
Comment (anuraaga) [reply instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/BaseTracer.java:311]: Hmm - I guess it probably should have the logic, let's do it in a separate PR since we might get lucky and solve our context leak issues before migrating to ServerInstrumenter? :P :D

**Review by trask — APPROVED** [review]
> Resetting to root was always a hack that we accepted out of necessity for leaking instrumentations. But we reached the end of the line :) Context is a shared resource and who knows what's been added to it before we get a chance to create a span, resetting it arbitrarily isn't really allowed. This new version is still not ideal but at least improves the situation a bit.
>
> Fixes #2853

👍
