### PR TITLE
Fix references to old artifact name

### LINKED ISSUE #655: Encountering NPE on bootstrapping with java agent
as is shown in the following, the error won't actually influence the tracer from running:

```
[opentelemetry.auto.trace 2020-07-09 16:21:10:188 +0800] [main] ERROR io.opentelemetry.auto.tooling.VersionLogger - failed to read version stream
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at io.opentelemetry.auto.tooling.VersionLogger.getVersionString(VersionLogger.java:48)
        at io.opentelemetry.auto.tooling.VersionLogger.logAllVersions(VersionLogger.java:32)
        at io.opentelemetry.auto.tooling.TracerInstaller.logVersionInfo(TracerInstaller.java:176)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.opentelemetry.auto.bootstrap.Agent.installAgentTracer(Agent.java:177)
        at io.opentelemetry.auto.bootstrap.Agent.start(Agent.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.opentelemetry.auto.bootstrap.AgentBootstrap.agentmain(AgentBootstrap.java:73)
        at io.opentelemetry.auto.bootstrap.AgentBootstrap.premain(AgentBootstrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[opentelemetry.auto.trace 2020-07-09 16:21:10:189 +0800] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: unknown
```

### PR DESCRIPTION
**Pull request by trask**
This part resolves #655:

```
getResourceAsStream("opentelemetry-javaagent.version")
```

### CODE REVIEW

File: agent-tooling/src/main/java/io/opentelemetry/auto/tooling/VersionLogger.java [hunk 1]
```diff
@@ -28,9 +28,10 @@
   /** Log version string for java-agent */
   public static void logAllVersions() {
     log.info(
-        "opentelemetry-auto - version: {}",
+        "opentelemetry-javaagent - version: {}",
         getVersionString(
-            ClassLoader.getSystemClassLoader().getResourceAsStream("opentelemetry-auto.version")));
+            ClassLoader.getSystemClassLoader()
+                .getResourceAsStream("opentelemetry-javaagent.version")));
```
Comment (anuraaga) [inline agent-tooling/src/main/java/io/opentelemetry/auto/tooling/VersionLogger.java:34]: Just a thought while we're here what do you think about moving the file to a package?

Comment (trask) [reply agent-tooling/src/main/java/io/opentelemetry/auto/tooling/VersionLogger.java:34]: It's a good thought, I opened #669 to discuss/track.
