### PR TITLE
Include status code for HttpUrlConnection exceptions

### LINKED ISSUE #2244: http-url-connection instrumentation creates on error spans without http.status_code attribute
**Describe the bug**

Spans for HTTP calls made with _HttpURLConnection_ or a client like _RestTemplate_ from Spring Boot, which uses it, have no `http.status_code` attribute on errors with response status 4xx and 5xx. If a response has status 1xx, 2xx or 3xx the attribute is present.

| **Status 1xx, 2xx and 3xx**          | **Status 4xx and 5xx**               |
| -------------------------------------------- | ----------------------------------------- |
| http-status-200 | http-status-500 |

**Steps to reproduce**

I've created a sample project to reproduce this issue at [https://github.com/rkondrashov/opentelemetry-span-without-status](https://github.com/rkondrashov/opentelemetry-span-without-status).

1. Build the project with `mvn clean package`.
2. Start the service, httpbin and jaeger using `docker-compose up -d` and wait until all components are started.
3. Call `./calls.sh` script to perform some HTTP calls to the service.
4. Take a look at traces in jaeger UI - [http://localhost:16686](http://localhost:16686).
5. Stop all components using `docker-compose down`.

Alternatively the service could be started without docker:

1. Build the project with `mvn -Dexec.skip clean package`.
2. Start the service:
```bash
java -javaagent:path/to/opentelemetry-javaagent-all.jar \
       -Dotel.traces.exporter=logging \
       -Dotel.metrics.exporter=none \
       -jar target/opentelemetry-span-without-status-1.0.0.jar \
       --httpbin.uri=https://httpbin.org/status
```
3. Call `./calls.sh` script to perform some HTTP calls to the service. 

**What did you expect to see?**

Spans on error with response status 4xx or 5xx have the `http.status_code` attribute.

**What did you see instead?**

The attribute `http.status_code` in spans on error with response status 4xx or 5xx missing.

**What version are you using?**

v0.16.0

**Environment**
Compiler: AdoptOpenJDK 11.0.9
OS: Mint 20.1

**Additional context**

The same issue with java agent v0.13.x, v0.14.x and v0.15.x.

### PR DESCRIPTION
**Pull request by breedx-splk**
Resolves #2244 

The `HttpUrlConnection` implementation is highly complex.  There are code paths that generate and throw an exception, which causes inconsistency around `responseCode` being populated or not (since it is both a method an a field).

There's also a neat note in the instrumentation module that says:
```
        // responseCode field is sometimes not populated.
        // We can't call getResponseCode() due to some unwanted side-effects
        // (e.g. breaks getOutputStream).
```

So this adds instrumentation around `HttpUrlConnection.getResponseCode()`.  Method enter is effectively a no-op, but on exit we get the span and add in the status code and mark it as an error if it's 400/500 level.

### CODE REVIEW

File: instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java [hunk 1]
```diff
@@ -85,8 +89,13 @@ public static void methodEnter(
         @Advice.FieldValue("connected") boolean connected,
         @Advice.Local("otelHttpUrlState") HttpUrlState httpUrlState,
         @Advice.Local("otelScope") Scope scope,
-        @Advice.Local("otelCallDepth") CallDepth callDepth) {
+        @Advice.Local("otelCallDepth") CallDepth callDepth,
+        @Advice.Origin("#m") String methodName) {
 
+      if (methodName.equals("getResponseCode")) {
```
Comment (mateuszrzeszutek) [inline instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java:95]: It looks like for `getResponseCode()` instrumentation has nothing in common with the other instrumented methods -- consider extracting it to a separate advice class and just put another map entry in the `transformers()` map.

File: instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java [hunk 2]
```diff
@@ -126,7 +135,23 @@ public static void methodExit(
...
+        ContextStore<HttpURLConnection, HttpUrlState> storage =
+            InstrumentationContext.get(HttpURLConnection.class, HttpUrlState.class);
+        httpUrlState = storage.get(connection);
+        if (httpUrlState != null) {
+          Span span = Span.fromContext(httpUrlState.context);
+          span.setAttribute(SemanticAttributes.HTTP_STATUS_CODE, (int) returnValue);
+          if ((int) returnValue >= 400) {
+            span.setStatus(StatusCode.ERROR);
+          }
```
Comment (mateuszrzeszutek) [inline instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java:150]: Please use `HttpStatusConverter` - same as `HttpClientTracer` does.

**Review by mateuszrzeszutek — COMMENTED** [review]
I also have an alternative idea: consider putting status code in `HttpUrlState` and using this new field to create a `HttpUrlResponse` - this way you won't have to set attributes yourself, you'll be able to rely on the tracer to do so.

**Review by iNikem — COMMENTED** [review]
What @mateuszrzeszutek said.

File: instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java (hunk 1 above)
Comment (breedx-splk) [reply instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java:95]: Yeah, if you look at the earlier commits I did have a new field in the `HttpUrlState` class, but it is only a local and isn't shared with the other advice calls for the other methods.  I will see what it looks like with a new advice.

Comment (breedx-splk) [reply instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java]: I think it's an improvement.  Thanks for the nudge.

**Review by iNikem — APPROVED** [review]

File: instrumentation/http-url-connection/javaagent/src/test/groovy/HttpUrlConnectionTest.groovy [hunk 3]
```diff
@@ -293,6 +294,28 @@ class HttpUrlConnectionTest extends HttpClientTest {
     }
   }
 
+  def "error span"(){
+    def uri = server.address.resolve("/error")
+    when:
+    def url = uri.toURL()
+    runUnderTrace("parent") {
+      doRequest(method, uri, ["is-test-server": "false"])
```
Comment (trask) [inline instrumentation/http-url-connection/javaagent/src/test/groovy/HttpUrlConnectionTest.groovy:302]: and then see below for corresponding validation
```suggestion
      doRequest(method, uri)
```

File: instrumentation/http-url-connection/javaagent/src/test/groovy/HttpUrlConnectionTest.groovy [hunk 4]
```diff
@@ -293,6 +294,28 @@ class HttpUrlConnectionTest extends HttpClientTest {
...
+    }
+
+    then:
+    def expectedException = new IOException("Server returned HTTP response code: 500 for URL: $url")
+    thrown(IOException)
+    assertTraces(1) {
+      trace(0, 2 + extraClientSpans()) {
+        basicSpan(it, 0, "parent", null, expectedException)
+        clientSpan(it, 1, span(0), method, uri, 500, expectedException)
+      }
```
Comment (trask) [inline instrumentation/http-url-connection/javaagent/src/test/groovy/HttpUrlConnectionTest.groovy:312]: there's no need for extraClientSpans() below, since that's not overridden in this test, but let's keep it, b/c I think we should move this test up to HttpClientTest - I'll open separate issue for that
```suggestion
      trace(0, 3 + extraClientSpans()) {
        basicSpan(it, 0, "parent", null, expectedException)
        clientSpan(it, 1, span(0), method, uri, 500, expectedException)
        serverSpan(it, 2 + extraClientSpans(), span(1 + extraClientSpans()))
      }
```

**Review by trask — APPROVED** [review]
👍

Btw, I hadn't noticed previously that we don't test the `/error` url from `HttpClientTest`. I'll open a separate issue to move your new `/error` test up to `HttpClientTest`.

**Review by mateuszrzeszutek — APPROVED** [review]

File: instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java [hunk 5]
```diff
@@ -148,6 +158,24 @@ public static void methodExit(
     }
   }
 
+  public static class GetResponseCodeAdvice {
+
+    @Advice.OnMethodExit
+    public static void methodExit(
+        @Advice.This HttpURLConnection connection,
+        @Advice.Return(typing = Assigner.Typing.DYNAMIC) int returnValue) {
```
[the remark this answers is not in the document]
Comment (breedx-splk) [reply instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java:166]: Good catch, that was a carry-over from when they were combined.  I should have caught it when I changed the type.  :). Will fix.
