### PR TITLE
[Spring starter] Add cache to reduce environment variable lookups

### LINKED ISSUE #15009: Performance issue in SpringConfigProperties#getInt due to lack of caching
### Describe the bug

[cpu-flame.html](https://github.com/user-attachments/files/22948010/cpu-flame.html)

Image

I uploaded a flamegraph showing a CPU hotspot during log processing, From the flamegraph, we can see that logging is slow, and the root cause is:

io.opentelemetry.instrumentation.spring.autoconfigure.internal.properties.SpringConfigProperties#getInt

Because AutoConfiguredOpenTelemetrySdk does not have @ConditionalOnMissingBean, I cannot override SpringConfigProperties gracefully.

Image

Temporary workaround I implemented:

I wrapped SpringConfigProperties with a caching layer that handles null values using Optional:

`public class CacheProperties implements ConfigProperties {
    // ConcurrentHashMap don't cache null
    private final Map<String, Optional<Object>> cache = new ConcurrentHashMap<>();

    private SpringConfigProperties delegate;

    public CacheProperties(SpringConfigProperties springConfigProperties) {
        this.delegate = springConfigProperties;
    }

    @Nullable
    @Override
    public String getString(String name) {
        return (String) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getString(name))).orElse(null);
    }

    @Override
    public Map<String, String> getMap(String name) {
        return (Map<String, String>) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getMap(name))).orElse(null);
    }

    @Nullable
    @Override
    public Duration getDuration(String name) {
        return (Duration) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getDuration(name))).orElse(null);
    }

    @Override
    public List<String> getList(String name) {
        return (List<String>) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getList(name))).orElse(null);
    }

    @Nullable
    @Override
    public Double getDouble(String name) {
        return (Double) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getDouble(name))).orElse(null);
    }

    @Nullable
    @Override
    public Integer getInt(String name) {
        return (Integer) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getInt(name))).orElse(null);
    }

    @Nullable
    @Override
    public Long getLong(String name) {
        return (Long) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getLong(name))).orElse(null);
    }

    @Nullable
    @Override
    public Boolean getBoolean(String name) {
        return (Boolean) cache.computeIfAbsent(name, k -> Optional.ofNullable(delegate.getBoolean(name))).orElse(null);
    }

}` 

And then I updated the factory method:

    public static ConfigProperties create(
            Environment env,
            OtlpExporterProperties otlpExporterProperties,
            OtelResourceProperties resourceProperties,
            OtelSpringProperties otelSpringProperties,
            ConfigProperties fallback) {
   
        return new CacheProperties(new SpringConfigProperties(
                env,
                new SpelExpressionParser(),
                otlpExporterProperties,
                resourceProperties,
                otelSpringProperties,
                fallback));
    }

This workaround greatly improves performance for repeated property lookups.

### Steps to reproduce

Configure OpenTelemetry with AutoConfiguredOpenTelemetrySdk in a Spring Boot application.

Enable logging at INFO/DEBUG level so that many logs are emitted.

Emit a large number of log statements (e.g., loop over forEach on a collection of log entries).

Observe that SpringConfigProperties#getInt becomes a CPU hotspot in profiling or flamegraphs.

[cpu-flame.html](https://github.com/user-attachments/files/22948269/cpu-flame.html)

### Expected behavior

Accessing configuration properties via SpringConfigProperties should be efficient and not incur high CPU usage during frequent logging.

The auto-configuration should allow overriding or replacing SpringConfigProperties gracefully, for example by supporting @ConditionalOnMissingBean, so users can provide a cached or customized implementation without having to fork the library.

### Actual behavior

Frequent access to configuration properties via SpringConfigProperties causes significant CPU usage and slows down logging. The class is eagerly instantiated and does not support graceful overriding because AutoConfiguredOpenTelemetrySdk does not use @ConditionalOnMissingBean, forcing users to implement workarounds like wrapping it with a custom caching layer.

### Javaagent or library instrumentation version

io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.20.1

### Environment

**JDK**:  Azul Zulu 21.0.7
**OS**: macos

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jaydeluca**
Fixes #15009

Add ability for users to customize AutoConfiguredOpenTelemetrySdk, and add cache for environment config lookups.

### CODE REVIEW

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java [hunk 1]
```diff
@@ -151,106 +170,166 @@ public static ConfigProperties create(
...
+              switch (normalizedName) {
+                case "otel.resource.attributes":
+                  return Optional.of(mergeWithOtel(resourceProperties.getAttributes(), otelSdkMap));
+                case "otel.exporter.otlp.headers":
+                  return Optional.of(
+                      mergeWithOtel(otlpExporterProperties.getHeaders(), otelSdkMap));
+                case "otel.exporter.otlp.logs.headers":
+                  return Optional.of(
+                      mergeWithOtel(otlpExporterProperties.getLogs().getHeaders(), otelSdkMap));
+                case "otel.exporter.otlp.metrics.headers":
```
Comment (zeitlinger) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java]: It looks like this is copied from somewhere - and could be extracted into a method

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java [hunk 2]
```diff
@@ -151,106 +170,166 @@ public static ConfigProperties create(
...
+        .orElse(null);
   }
 
   @Nullable
   @Override
   public Long getLong(String name) {
-    return or(
-        environment.getProperty(ConfigUtil.normalizeEnvironmentVariableKey(name), Long.class),
-        otelSdkProperties.getLong(name));
+    return cachedLongValues
```
Comment (zeitlinger) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java]: Looks like a generic method could be extracted to shorten this and below methods

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java (hunk 1 above)
Comment (jaydeluca) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java]: i didnt see anywhere else that this is being used, but i extracted it anyway, makes things cleaner

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java [hunk 3]
```diff
@@ -148,89 +168,155 @@ public static ConfigProperties create(
...
+    return cache
+        .computeIfAbsent(name, key -> Optional.ofNullable(valueFunction.apply(key)))
+        .orElse(null);
+  }
+
   @Nullable
   @Override
   public String getString(String name) {
-    String normalizedName = ConfigUtil.normalizeEnvironmentVariableKey(name);
-    String value = environment.getProperty(normalizedName, String.class);
```
Comment (laurit) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java:155]: An alternative approach that could be considered would be to wrap the `environment` into a caching `PropertyResolver`. I presume that the sdk deliberately rereads these properties so they could be updated with opamp in the future. Idk whether this is something we should be concerned with.

Comment (zeitlinger) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java:155]: > I presume that the sdk deliberately rereads these properties

no, it was not a deliberate decision as far as I know.

When I worked on the project, I assumed that properties would only be read at startup time.

I think it's hard to anticipate how OpAMP will be integrated, but we may simply flush the cache (from the caching `PropertyResolver`.

Comment (jaydeluca) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java:155]: implemented a caching property resolver, and included a way to flush the cache

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java [hunk 4]
```diff
@@ -100,6 +100,7 @@ public ResourceProvider otelDistroVersionResourceProvider() {
     }
 
     @Bean
+    @ConditionalOnMissingBean
```
Comment (zeitlinger) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: why?

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java [hunk 5]
```diff
@@ -44,7 +44,7 @@ public SpringConfigProperties(
       OtelResourceProperties resourceProperties,
       OtelSpringProperties otelSpringProperties,
       ConfigProperties otelSdkProperties) {
-    this.environment = environment;
+    this.cachedEnvironment = new CachedPropertyResolver(environment);
```
Comment (zeitlinger) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/SpringConfigProperties.java]:
```suggestion
    this.environment = new CachedPropertyResolver(environment);
```

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java (hunk 4 above)
Comment (jaydeluca) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: i added this to allow people to customize the behavior, if they wanted

Comment (zeitlinger) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: we already have https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2e450ea949976f5ef7f53b82713d7c674a81e677/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L83 - which I feel is enough, but feel free to create a separate PR to discuss

Comment (jaydeluca) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: in the original issue #15009 they asked to be able to override this:

> The auto-configuration should allow overriding or replacing SpringConfigProperties gracefully, for example by supporting @ConditionalOnMissingBean, so users can provide a cached or customized implementation without having to fork the library.

But since we addressed the performance issue, perhaps it's less necessary?

Comment (zeitlinger) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: yes, I think so

adding `@ConditionalOnMissingBean` increases the API surface area in ways that also increase complexity

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/CachedPropertyResolver.java [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+  @Nullable
+  <T> T getProperty(String name, Class<T> targetType) {
+    CacheKey key = new CacheKey(name, targetType);
+    // CacheKey includes targetType, ensuring type match
+    @SuppressWarnings("unchecked")
+    Optional<T> result =
+        (Optional<T>)
+            cache.computeIfAbsent(
+                key, k -> Optional.ofNullable(environment.getProperty(name, targetType)));
+    return result.orElse(null);
```
Comment (laurit) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/CachedPropertyResolver.java]: What does using `Optional` give over just using 
`return targetType.cast(cache.computeIfAbsent(key, k -> environment.getProperty(name, targetType)));`

Comment (jaydeluca) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/internal/properties/CachedPropertyResolver.java]: ConcurrentHashMap doesn't store `null` values, so if the lookup returns null it'll keep checking the environment instead of caching it
