### PR TITLE
Don't create duplicate headers

### LINKED ISSUE #2594: HttpHeadersInjectAdapter should use 'setHeader' instead of 'addHeader'?
**Describe the bug**
If reuse http request, traceparent header will be more and more when use apache-httpclient4.x and 5.x

image

**What version are you using?**
v1.0.1

### PR DESCRIPTION
**Pull request by trask**
Resolves #2594

Adds a new test to `HttpClientTest` that create a request, sends the request, and then reuses that request (sending it a second time).

Most of the http client libraries support this kind of reuse, and several of our instrumentations would end up adding the `traceparent` header multiple times (#2594).

`HttpTestServer` now throws an exception if there is more than one `traceparent` header.

To implement the new test, the `doRequest()` method that was implemented in each subclass of `HttpClientTest` has been split into two methods:
* `buildRequest()`
* `sendRequest()`

The normal `doRequest` (now final) is implemented as `buildRequest` + `sendRequest`, while the new `doReusedRequest` (also final) is implemented as `buildRequest` + `sendRequest` + `sendRequest`.

### CODE REVIEW

File: testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/server/http/TestHttpServer.groovy [hunk 1]
```diff
@@ -249,6 +249,10 @@ class TestHttpServer implements AutoCloseable {
         isTestServer = Boolean.parseBoolean(request.getHeader("is-test-server"))
       }
       if (isTestServer) {
+        def headers = req.getHeaders("traceparent")
```
Comment (mateuszrzeszutek) [inline testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/server/http/TestHttpServer.groovy:252]: Should we use `GlobalOpenTelemetry.getPropagators().getTextMapPropagator().fields()` instead of hardcoding `traceparent`?

File: testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/base/HttpClientTest.groovy [hunk 2]
```diff
@@ -104,18 +129,18 @@ abstract class HttpClientTest extends InstrumentationSpecification {
...
    * @Override
-   * int doRequest(String method, URI uri, Map<String, String headers = [:]) {
+   * int sendRequest(REQUEST request, String method, URI uri, Map<String, String> headers) {
    *   CompletableFuture<Integer> result = new CompletableFuture<>()
    *   doRequestWithCallback(method, uri, headers) {
    *     result.complete(it.statusCode())
    *   }
    *   return result.join()
    * }
    */
```
Comment (mateuszrzeszutek) [inline testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/base/HttpClientTest.groovy:139]: Can you update the whole Javadoc so that is does not mention `new Request()` or `doRequest()`?

Also, would it make sense to refactor `doRequestWithCallback()` in a similar way to `doRequest()`? Make it final and split into `buildRequest()` + `sendRequestWithCallback()`

File: instrumentation/akka-http-10.0/javaagent/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy [hunk 3]
```diff
@@ -9,43 +9,45 @@ import akka.actor.ActorSystem
...
+    return Http.get(system)
+      .singleRequest(request, materializer)
+      .toCompletableFuture()
+      .get()
+      .status()
+      .intValue()
   }
 
   @Override
   void doRequestWithCallback(String method, URI uri, Map<String, String> headers = [:], Consumer<Integer> callback) {
```
Comment (anuraaga) [inline instrumentation/akka-http-10.0/javaagent/src/test/groovy/AkkaHttpClientInstrumentationTest.groovy:44]: Can we pass request into this one too?

File: testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/server/http/TestHttpServer.groovy (hunk 1 above)
Comment (trask) [reply testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/server/http/TestHttpServer.groovy]: oh good idea!

File: instrumentation/http-url-connection/javaagent/src/test/groovy/SpringRestTemplateTest.groovy [hunk 4]
```diff
@@ -28,22 +27,28 @@ class SpringRestTemplateTest extends HttpClientTest implements AgentTestTrait {
   }
 
   @Override
-  int doRequest(String method, URI uri, Map<String, String> headers = [:]) {
+  Void buildRequest(String method, URI uri, Map<String, String> headers) {
+    return null
```
Comment (anuraaga) [inline instrumentation/http-url-connection/javaagent/src/test/groovy/SpringRestTemplateTest.groovy:31]: Should we set `testReusedRequest` to false to be explicit about it not being tested (I guess it's not being tested)?

**Review by anuraaga — APPROVED** [review]

File: instrumentation/http-url-connection/javaagent/src/test/groovy/SpringRestTemplateTest.groovy (hunk 4 above)
Comment (trask) [reply instrumentation/http-url-connection/javaagent/src/test/groovy/SpringRestTemplateTest.groovy]: pushed a new commit that seems a bit better, lmk

**Review by mateuszrzeszutek — APPROVED** [review]
