### PR TITLE
Fix muzzle and add missing helper classes

### LINKED ISSUE #1584: JDBC instrumentation does not work
**Describe the bug**
When I tried an JDBC hello world example in a Spring boot application, I could not find the span that contains query information. After opening the debug logs of the agent I saw this error message:

```
java.lang.NoClassDefFoundError: io/opentelemetry/javaagent/instrumentation/jdbc/JDBCConnectionUrlParser
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.extractDbInfo(JdbcTracer.java:106)
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.startSpan(JdbcTracer.java:77)
	at io.opentelemetry.javaagent.instrumentation.jdbc.JdbcTracer.startSpan(JdbcTracer.java:68)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.example.demo.MyRest.jdbc(MyRest.java:31)
```

**Steps to reproduce**
I saw the error in a JDBC select example written in a Spring boot hello world application. The database is Postgres.

**What did you expect to see?**
A span that contains query information.

**What did you see instead?**
Span does not exist. NoClassDefFoundError thrown instead.

**What version are you using?**
Latest snapshot **opentelemetry-javaagent-0.10.0-20201106.042347-58-all**
v0.9.0 works as expected.

**Environment**
OS: Windows 10 
Runtime: "Oracle JDK 11.0.9"

### PR DESCRIPTION
**Pull request by trask**
Fixes #1584

### CODE REVIEW

File: instrumentation/jdbc/src/main/java/io/opentelemetry/javaagent/instrumentation/jdbc/StatementInstrumentation.java [hunk 1]
```diff
@@ -46,7 +46,30 @@ public StatementInstrumentation() {
   @Override
   public String[] helperClassNames() {
     return new String[] {
-      packageName + ".JDBCMaps", packageName + ".JDBCUtils", packageName + ".JdbcTracer",
+      packageName + ".DataSourceTracer",
+      packageName + ".DBInfo",
+      packageName + ".DBInfo$Builder",
+      packageName + ".JDBCConnectionUrlParser",
+      packageName + ".JDBCConnectionUrlParser$1",
```
Comment (anuraaga) [inline instrumentation/jdbc/src/main/java/io/opentelemetry/javaagent/instrumentation/jdbc/StatementInstrumentation.java:53]: Yikes

**Review by anuraaga — APPROVED** [review]

**Review by iNikem — APPROVED** [review]
How did it happen that none of our tests found it?

**Comment by trask** [comment]
> How did it happen that none of our tests found it?

Ya this is good question. The problem is that those helper classes are already on the classpath when the tests run, so we don't notice if they aren't injected.
