### PR TITLE
When loading exporter factories via SPI from an external jar, look only inside that jar, and not any parent classloader.

### LINKED ISSUE #542: Installing a metric exporter from an external jar fails when using the auto-instrumentation auto-all jar for the agent.
I get this message when trying to install:
```
WARN io.opentelemetry.auto.tooling.TracerInstaller - Exporter JAR defines more than one
```
and it proceeds to load the OTLP exporter.

Note 1: this works fine for a SpanExporter. 
Note 2: it works if I don't use the opentelemetry-auto-all.jar, but instead just use the opentelemetry-auto.jar version.

### PR DESCRIPTION
**Pull request by iNikem**
Fixes #542

### CODE REVIEW

**Comment by iNikem** [comment]
@jkwatson 
```
[opentelemetry.auto.trace 2020-06-23 21:36:31:301 +0300] [main] INFO com.newrelic.telemetry.transport.BatchDataSender - BatchDataSender configured with endpoint https://trace-api.newrelic.com/trace/v1
[opentelemetry.auto.trace 2020-06-23 21:36:31:337 +0300] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed span exporter: com.newrelic.telemetry.opentelemetry.export.NewRelicSpanExporter
[opentelemetry.auto.trace 2020-06-23 21:36:31:347 +0300] [main] INFO com.newrelic.telemetry.transport.BatchDataSender - BatchDataSender configured with endpoint https://metric-api.newrelic.com/metric/v1
[opentelemetry.auto.trace 2020-06-23 21:36:31:350 +0300] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed metric exporter: com.newrelic.telemetry.opentelemetry.export.NewRelicMetricExporter
[opentelemetry.auto.trace 2020-06-23 21:36:31:353 +0300] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: 0.5.0-SNAPSHOT~918d3913e
```

File: agent-tooling/src/test/groovy/io/opentelemetry/auto/tooling/ExporterClassLoaderTest.groovy [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+import io.opentelemetry.sdk.contrib.auto.config.MetricExporterFactory
+import io.opentelemetry.sdk.contrib.auto.config.SpanExporterFactory
+import io.opentelemetry.sdk.metrics.export.MetricExporter
+import io.opentelemetry.sdk.trace.export.SpanExporter
+import java.nio.charset.StandardCharsets
+import java.util.jar.JarEntry
+import java.util.jar.JarOutputStream
+import spock.lang.Specification
+
+class ExporterClassLoaderTest extends Specification {
```
Comment (trask) [inline agent-tooling/src/test/groovy/io/opentelemetry/auto/tooling/ExporterClassLoaderTest.groovy:29]: 👍
