### PR TITLE
fix MapConverter bean condition

### LINKED ISSUE #10344: MapConverter does not get initialized if some exporters are turned off
### Describe the bug

The `MapConverter` for `OTEL_RESOURCE_ATTRIBUTES` uses a `ConditionalOnBean` statement, that only includes it in the context if multiple exporter beans are in context at the same time: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/bc034f3b1b8d66e6c9f5a133407922278bc87086/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L66-L77

This, however, means that if only one of them us turned off (e.g. you do not want to use the logger exporter), and the resource attributes are set, the context initialization will fail with:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]
```

### Steps to reproduce

1. Set up a Spring Boot sample project with OTEL as specified in https://opentelemetry.io/docs/languages/java/automatic/spring-boot/
2. In envvars, include a sample `OTEL_RESOURCE_ATTRIBUTES` map (e.g. `var1=sample1,var2=sample2`), and turn off one of the exporters.
3. Run the application.

### Expected behavior

The application starts up.

### Actual behavior

The application startup fails on
```
Could not bind properties to 'OtelResourceProperties' : prefix=otel.resource, ignoreInvalidFields=false, ignoreUnknownFields=true","context":"default"}
```
due to 
```
 Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]
 ```

### Javaagent or library instrumentation version

1.34.1

### Environment

**JDK**: Corretto 21
**OS**: MacOS Ventura
Spring Boot 3.2.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zeitlinger**
Fixes #10344

### CODE REVIEW

File: smoke-tests-otel-starter/src/test/java/io/opentelemetry/smoketest/OtelSpringStarterSmokeTest.java [hunk 1]
```diff
@@ -36,8 +36,13 @@
       OtelSpringStarterSmokeTest.TestConfiguration.class
     },
     webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
-    properties = {"otel.exporter.otlp.enabled=false", "otel.metric.export.interval=100"
+    properties = {
+      "otel.exporter.otlp.enabled=false",
+      "otel.metric.export.interval=100",
+      "otel.exporter.otlp.headers=a=1,b=2",
```
[the remark this answers is not in the document]
Comment (zeitlinger) [reply smoke-tests-otel-starter/src/test/java/io/opentelemetry/smoketest/OtelSpringStarterSmokeTest.java:42]: I tried to do that - then found out that context runner works differently - bean conditions are only evaluated with a `@SpringBootTest`

**Review by jeanbisutti — APPROVED** [review]

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java [hunk 2]
```diff
@@ -65,17 +67,31 @@ public static class OpenTelemetrySdkConfig {
...
+              OtlpSpanExporterAutoConfiguration.class,
+              OtlpMetricExporterAutoConfiguration.class);
+
+      @Override
+      public boolean matches(
+          org.springframework.context.annotation.ConditionContext context,
+          org.springframework.core.type.AnnotatedTypeMetadata metadata) {
+
+        return ANY_REQUIRED_BEANS.stream()
+            .anyMatch(s -> context.getBeanFactory().containsBean(s.getName()));
```
Comment (laurit) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java:91]: while this checks for presence of a bean by name the javadoc in https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnBean.html indicates that it checks by type. Would it make sense to keep that behavior? Perhaps it would work if you'd use something like https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnBean.html where you put `@ConditionalOnBean` for each of these classes on a separate nested class?

File: instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java [hunk 3]
```diff
@@ -65,17 +67,31 @@ public static class OpenTelemetrySdkConfig {
...
+              OtlpSpanExporterAutoConfiguration.class,
+              OtlpMetricExporterAutoConfiguration.class);
+
+      @Override
+      public boolean matches(
+          org.springframework.context.annotation.ConditionContext context,
+          org.springframework.core.type.AnnotatedTypeMetadata metadata) {
+
+        return ANY_REQUIRED_BEANS.stream()
+            .anyMatch(s -> context.getBeanFactory().getBeanProvider(s).getIfAvailable() != null);
```
Comment (laurit) [inline instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java:91]: you sure this is safe? As far as I understand this creates the actual bean instance while https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnBeanCondition.java doesn't

Comment (laurit) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java:91]: I suspect that when you create the beans too early you could run into something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9988 I pasted the wrong like into my previous comment (update it) as a sample of how this might be done https://www.baeldung.com/spring-conditional-annotations#combining-conditions I have not tried it myself so no idea whether this would actually work. I was thinking that if you could have `@ConditionalOnBean` on nested classes then perhaps this would have less chances of breaking in a strange way.

Comment (zeitlinger) [reply instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java]: learned something new :smile: 

That's indeed a good argument to use the nested conditions - done!

**Comment by trask** [comment]
@zeitlinger looks like there's a test failure
