### PR TITLE
Fix #8462 - Use more permissive regexp to extract containerid

### LINKED ISSUE #8462: Container id may be incorrect if cgroup v2 is used
When running in a cgroup v2 container, the Java agent attempts to discover the container-id by reading `/proc/self/mountinfo` and adds it to the reported Resources. However, it has been observed that the container id from that file may be incorrect.

Running from within container:
```
cat /proc/self/mountinfo | grep hostname
1290 1281 254:1 /docker/containers/0c31511deaae072674a6f90929684d8e2d4138d424ea5717d1694da8dbd1796e/hostname /etc/hostname rw,relatime - ext4 /dev/vda1 rw
```

while the true container id  is different
```
kubectl  describe pod javatest1-685798bc98-vmldn | grep "Container ID"  
Container ID:   docker://1193d58b89b1704f18fbf9ee950b9e652fe5e1212345f9a1c161cc6782ccc0d7
```

To reproduce, use a recent version of docker (which uses cgroup v2) and kubernetes.

The code which reads /proc/self/mountinfo was added by this [PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7167)

### PR DESCRIPTION
**Pull request by stefanroeck**
This fixes #8462 by using a more strict regexp that doesn't match "/container" ocurrances in the option field area of the mountinfo file. 

Also report a warning, in case a unique containerId cannot be extracted and return the last one.

### CODE REVIEW

**Comment by trask** [comment]
thanks @stefanroeck! I'm going to convert your PR to draft until you're able to resolve the CLA, and then please mark it ready for review

File: instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java [hunk 1]
```diff
@@ -25,7 +25,8 @@ class CgroupV2ContainerIdExtractor {
       Logger.getLogger(CgroupV2ContainerIdExtractor.class.getName());
 
   static final Path V2_CGROUP_PATH = Paths.get("/proc/self/mountinfo");
-  private static final Pattern CONTAINER_ID_RE = Pattern.compile("^[0-9a-f]{64}$");
+  private static final Pattern CONTAINER_ID_RE =
+      Pattern.compile("^[0-9 :]+[/a-z]*/containers/.*([0-9a-f]{64})/.*$");
```
Comment (laurit) [inline instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java]: wondering whether `Pattern.compile("^[0-9 :]+[^ ]*/containers/.*([0-9a-f]{64})/.*$");` would be better

Comment (stefanroeck) [reply instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java]: done

File: instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java [hunk 2]
```diff
@@ -25,7 +25,8 @@ class CgroupV2ContainerIdExtractor {
       Logger.getLogger(CgroupV2ContainerIdExtractor.class.getName());
 
   static final Path V2_CGROUP_PATH = Paths.get("/proc/self/mountinfo");
-  private static final Pattern CONTAINER_ID_RE = Pattern.compile("^[0-9a-f]{64}$");
+  private static final Pattern CONTAINER_ID_RE =
+      Pattern.compile("^[0-9 :]+[^ ]*/containers/.*([0-9a-f]{64})/.*$");
```
Comment (trask) [inline instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java]: Optional simplification: anchor on the mountinfo prefix and constrain `/containers/...<id>` to the root field (whitespace-free token), so option-field content like `lowerdir=...` can never contribute a match. Also lets you switch `Matcher::matches` to `Matcher::find` since the regex no longer needs a trailing `/.*$`.

```suggestion
      Pattern.compile("^\\d+ \\d+ \\d+:\\d+ [^ ]*/containers/[^ ]*?([0-9a-f]{64})");
```

File: instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java [hunk 3]
```diff
@@ -76,12 +77,19 @@ Optional<String> extractContainerId() {
...
+    List<String> containerIds =
+        fileAsList.stream()
+            .filter(line -> line.contains("/containers/"))
+            .map(CONTAINER_ID_RE::matcher)
+            .filter(Matcher::matches)
+            .map(matcher -> matcher.group(1))
+            .distinct()
+            .collect(toList());
+    if (containerIds.size() > 1) {
+      logger.log(WARNING, "Multiple container ids found in v2 cgroup path: " + containerIds);
```
Comment (trask) [inline instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java]:
```suggestion
      logger.log(WARNING, "Multiple container ids found in v2 cgroup path: {0}", containerIds);
```

File: instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java (hunk 2 above)
Comment (stefanroeck) [reply instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java]: Good idea, done.

**Review by trask — APPROVED** [review]
@breedx-splk if you have time can you have a look as well? thanks

**Review by laurit — APPROVED** [review]
