### PR TITLE
Muzzle should fail on unimplemented abstract methods

### LINKED ISSUE #1123: Muzzle should fail on unimplemented abstract methods
This is an idea for improvement that would have prevented something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1083 from happening.
In that issue, Servlet API 3.1 introduced two new abstract methods to `ServletOutputStream` that were unimplemented in our code -- and everything was OK until someone tried to call one of them.

I believe that muzzle should fail for an instrumentation if one of our classes that implements/extends some lib/framework class has missing methods.

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Resolves #1123

### CODE REVIEW

**Comment by trask** [comment]
Thank you for tackling this ❤️👍

**Comment by iNikem** [comment]
Hei, @mateuszrzeszutek, maybe you can help @trask with #536 ;)

**Comment by trask** [comment]
> Hei, @mateuszrzeszutek, maybe you can help @trask with #536 ;)

💯

@mateuszrzeszutek I will review this PR tomorrow 👍

**Comment by mateuszrzeszutek** [comment]
> Hei, @mateuszrzeszutek, maybe you can help @trask with #536 ;)

**Comment by mateuszrzeszutek** [comment]
> Hei, @mateuszrzeszutek, maybe you can help @trask with #536 ;)

Sure - after implementing this change I think I can answer at least half of these questions. I'll put it on my TODO list and push a PR soon.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java [hunk 1]
```diff
@@ -0,0 +1,278 @@
...
+            .filter(isOverrideable())
+            .transform(toMethod());
+      }
+
+      private Predicate<Reference.Method> isOverrideable() {
+        return new Predicate<Reference.Method>() {
+          @Override
+          public boolean apply(Reference.Method input) {
+            return !(input.getFlags().contains(Flag.STATIC)
+                || input.getFlags().contains(Flag.PRIVATE_OR_HIGHER)
```
Comment (iNikem) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java:180]: Is private method overridable?

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/MuzzleVisitor.java [hunk 2]
```diff
@@ -133,28 +133,18 @@ public MethodVisitor visitMethod(
     }
 
     public Reference[] generateReferences() {
-      // track sources we've generated references from to avoid recursion
```
Comment (iNikem) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/MuzzleVisitor.java:136]: Why this is not required any more?

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java [hunk 3]
```diff
@@ -363,25 +364,36 @@ public boolean matches(int asmFlags) {
...
-        return anotherFlag == NON_FINAL;
+        return anotherFlag == NON_FINAL || anotherFlag == ABSTRACT;
       }
 
       @Override
       public boolean matches(int asmFlags) {
         return (Opcodes.ACC_FINAL & asmFlags) != 0;
       }
     },
+    ABSTRACT {
```
Comment (iNikem) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java:386]: Can you add javadoc to methods of `Flag` enum?

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java [hunk 4]
```diff
@@ -147,7 +157,64 @@ private boolean doesMatch(ClassLoader loader) {
...
 
-  public static List<Reference.Mismatch> checkMatch(
+  // for helper classes we make sure that all abstract methods from super classes and interfaces are
+  // implemented
+  private List<Reference.Mismatch> checkHelperClassMatch(Reference helperClass, TypePool typePool) {
+    List<Mismatch> mismatches = Collections.emptyList();
+
+    HelperReferenceWrapper helperWrapper = new Factory(typePool, references).create(helperClass);
+
+    if (!helperWrapper.hasSuperTypes() || helperWrapper.isAbstract()) {
```
Comment (iNikem) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java:167]: Do we support abstract helpers?

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java [hunk 5]
```diff
@@ -147,7 +157,64 @@ private boolean doesMatch(ClassLoader loader) {
...
+    }
+  }
+
+  // ignore Object methods - sometimes defined by interfaces which causes them to be treated as
+  // abstract
+  private static boolean shouldIgnore(HelperReferenceWrapper.Method superMethod) {
+    return "hashCode".equals(superMethod.getName()) && "()I".equals(superMethod.getDescriptor())
+        || "equals".equals(superMethod.getName())
+            && "(Ljava/lang/Object;)Z".equals(superMethod.getDescriptor())
+        || "toString".equals(superMethod.getName())
```
Comment (iNikem) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java:213]: `clone` and `finalize`?

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java (hunk 4 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java:167]: We do -- we just skip the abstract method check for them, because it's perfectly fine for them to contain abstract methods.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java (hunk 5 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java:213]: Good catch, will add.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/MuzzleVisitor.java (hunk 2 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/MuzzleVisitor.java:136]: Because it served no purpose from the start: because `adviceClassNames` always contained unique elements `referenceSources.contains(adviceClass)` always returned false.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java (hunk 1 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java:180]: Nope, they're not - so we can skip checking them.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java (hunk 3 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java:386]: I'll add javadoc to `matches()` method -- I've checked the usages of all of them and it turned out that `contradicts()` and `supersedes()` are never used. I guess that I'll be doing a general code clean-up together with muzzle documentation 😄

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java (hunk 1 above)
Comment (iNikem) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java:180]: Now I am even more confused. We create a predicate for `isOverrideable` and we say it is `true` when method 

- is not static AND
- is not private or higher AND
- is not a constructor

aren't ALL methods "private or higher"? Which makes this predicate constantly `false`?

Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/HelperReferenceWrapper.java:180]: Ah, that's what you meant. The problem here is that `PRIVATE_OR_HIGHER` (and others) is used in two ways in muzzle:
1) it just simply marks that a method/class is private which is the case here, or
2) it describes a minimum access level required between a type and a method/field/class.

I'll split those two types of usage into separate flags to make it a bit more clear.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceCreator.java [hunk 6]
```diff
@@ -244,12 +253,68 @@ public FieldVisitor visitField(
   @Override
   public MethodVisitor visitMethod(
       int access, String name, String descriptor, String signature, String[] exceptions) {
+
+    // declared method references are not generated for advice classes, only for helper classes
```
Comment (trask) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceCreator.java:257]: maybe as an optimization here, don't generate method references for private methods, <init> or <clinit> since they can't implement an abstract method

**Review by trask — COMMENTED** [review]
have you tried to see if this would have caught the ServletOutputStream issue? i gave it a try, but muzzle still didn't fail for me on unimplemented ServletOutputStream methods

**Comment by mateuszrzeszutek** [comment]
> have you tried to see if this would have caught the ServletOutputStream issue? i gave it a try, but muzzle still didn't fail for me on unimplemented ServletOutputStream methods

You're right, I unknowingly introduced a bug when I was refactoring the first working version. Thanks for noticing it! I'll add a unit test that covers this specific scenario.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java [hunk 7]
```diff
@@ -295,62 +296,63 @@ String getMismatchDetails() {
...
       String getMismatchDetails() {
-        return "Missing method " + className + "#" + method;
+        return "Missing method " + className + "#" + methodSignature;
       }
     }
   }
 
   /** Expected flag (or lack of flag) on a class, method, or field reference. */
   public enum Flag {
+    // The following constants represent the exact visibility of a referenced class/method
```
[the remark this answers is not in the document]
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/Reference.java:316]: I thought about extracting a common `Flag` interface and making all these new enums implement it, but leaving them all in a single enum set. I like the separate fields idea because of how easy it'd be to detect merge conflicts (you can't have a field that is both static and non-static).

I'll do that in a separate PR - I'll refactor, clean up and document muzzle someday soon.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java [hunk 8]
```diff
@@ -147,7 +157,67 @@ private boolean doesMatch(ClassLoader loader) {
...
+      (method.isAbstract() ? abstractMethods : plainMethods).add(method);
+    }
+
+    for (HelperReferenceWrapper superType : type.getSuperTypes()) {
+      collectMethodsFromTypeHierarchy(superType, abstractMethods, plainMethods);
+    }
+  }
+
+  // ignore Object methods - sometimes defined by interfaces which causes them to be treated as
+  // abstract
```
[the remark this answers is not in the document]
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java:208]: Honestly I can't remember now why I stopped recursion before `Object` - I must have run into some issue with that, but I can't remember what it was. I've removed both this method and the `Object` condition in `HelperReferenceWrapper` and everything works as expected, so I'll remove this code altogether. The simpler it is the better.

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceCreator.java (hunk 6 above)
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceCreator.java:257]: That's a very good idea, I'll do that. Thanks!

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java [hunk 9]
```diff
@@ -147,7 +157,67 @@ private boolean doesMatch(ClassLoader loader) {
...
+    Set<HelperReferenceWrapper.Method> unimplementedMethods =
+        Sets.difference(abstractMethods, plainMethods);
+    for (HelperReferenceWrapper.Method unimplementedMethod : unimplementedMethods) {
+      mismatches =
+          lazyAdd(
+              mismatches,
+              new Reference.Mismatch.MissingMethod(
+                  helperClass.getSources().toArray(new Reference.Source[0]),
+                  helperClass.getClassName(),
+                  unimplementedMethod.toString()));
```
[the remark this answers is not in the document]
Comment (mateuszrzeszutek) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/ReferenceMatcher.java]: Good point, changed.

**Review by iNikem — APPROVED** [review]

**Review by trask — APPROVED** [review]
🎉🎉
