### PR TITLE
fix finding SpanExporterFactory by exporterName with underscore e.g. "otlp_span"

### LINKED ISSUE #1401: No otlp_span span exporter found
```
java -javaagent:opentelemetry-javaagent-0.9.0-all.jar \
   -Dotel.exporter=otlp_span \
   -jar target/opentelemetry-agent-example.jar 
[opentelemetry.auto.trace 2020-10-16 15:03:48:051 +0800] [main] WARN io.opentelemetry.javaagent.tooling.TracerInstaller - No otlp_span span exporter found
[opentelemetry.auto.trace 2020-10-16 15:03:48:070 +0800] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.9.0
```

In 0.9.0 release otlp_span exporter should be supported: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1253

cc @pavolloffay

### PR DESCRIPTION
**Pull request by malafeev**
fix #1401

### CODE REVIEW

File: javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java [hunk 1]
```diff
@@ -127,9 +127,8 @@ private static SpanExporterFactory findSpanExporterFactory(String exporterName)
       if (spanExporterFactory
           .getClass()
           .getSimpleName()
-          .replace("_", "")
           .toLowerCase()
-          .startsWith(exporterName.toLowerCase())) {
+          .startsWith(exporterName.replace("_", "").toLowerCase())) {
```
Comment (mateuszrzeszutek) [inline javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java:131]: We need to fix that black magic exporter matching soon...

Can you add the same fix to `MetricExporterFactory` and `MetricServer` methods?

Thanks!

Comment (trask) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java:131]: can we make it so that `otlpspan` does not work? I think better to be strict about only supporting the values in the spec https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md#exporter-selection

Comment (malafeev) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java]: done

Comment (trask) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java]: i think `otlpspan` will still work with latest change?

Comment (malafeev) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java]: @trask, yes, `otlpspan` still works. If I will check for strict list of supported values then how user will be able to specify custom exporter?

Comment (trask) [reply javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java]: ok, makes sense, we can tackle this later in #1287

**Review by trask — APPROVED** [review]

**Review by iNikem — APPROVED** [review]
