### PR TITLE
fix jul logger methods mismatch

### LINKED ISSUE #14530: Jul logger methods mismatch error
### Describe the bug

raleted to #14380 
PatchLogger implements all methods of JUL Logger, but some methods modifiers are mismatch, so it will throw such error like 
```
java.lang.IncompatibleClassChangeError: Expecting non-static method 'void io.opentelemetry.javaagent.bootstrap.PatchLogger.setUseParentHandlers(boolean)'
```

### Steps to reproduce

the same with #14380

### Expected behavior

start up success and no error log

### Actual behavior

```
java.lang.IncompatibleClassChangeError: Expecting non-static method 'void io.opentelemetry.javaagent.bootstrap.PatchLogger.setUseParentHandlers(boolean)'
```

### Javaagent or library instrumentation version

2.19.0

### Environment

**JDK**: 21
**OS**: macos

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by xiangtianyu**
fix #14530 
PatchLogger and JUL Logger methods should keep same with modifiers

### CODE REVIEW

File: javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap/PatchLogger.java [hunk 1]
```diff
@@ -340,19 +340,19 @@ public static PatchLogger getAnonymousLogger(String resourceBundleName) {
     return getLogger("");
   }
 
-  public static PatchLogger getGlobal() {
+  public static final PatchLogger getGlobal() {
```
Comment (laurit) [inline javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap/PatchLogger.java]: Matching the `final` modifier isn't important, only `static` is.

File: javaagent-bootstrap/src/test/java/io/opentelemetry/javaagent/bootstrap/PatchLoggerTest.java [hunk 2]
```diff
@@ -804,18 +808,19 @@ public boolean equals(@Nullable Object obj) {
       MethodSignature other = (MethodSignature) obj;
       return Objects.equals(name, other.name)
           && Objects.equals(parameterTypes, other.parameterTypes)
-          && Objects.equals(returnType, other.returnType);
+          && Objects.equals(returnType, other.returnType)
+          && modifiers == other.modifiers;
```
Comment (laurit) [inline javaagent-bootstrap/src/test/java/io/opentelemetry/javaagent/bootstrap/PatchLoggerTest.java]: might be better to use `Modifier.isStatic(modifiers) == Modifier.isStatic(other.modifiers)`

**Review by laurit — APPROVED** [review]
