### PR TITLE
Move java files to java source folder and groovy files to groovy source folder

### LINKED ISSUE #1653: Move java test classes from src/test/groovy to src/test/java
Java test files seem to be split between `src/test/groovy` and `src/test/java`.

Probably they should all be under `src/test/java`(?)

Here's current list:

```
$ find -name *.java | grep groovy
./instrumentation/jaxrs/jaxrs-1.0/src/test/groovy/JavaInterfaces.java
./instrumentation/servlet/glassfish-testing/src/test/groovy/TestServlets.java
./instrumentation/servlet/servlet-3.0/src/test/groovy/RequestDispatcherServlet.java
./instrumentation/servlet/servlet-common/src/test/groovy/RequestDispatcherUtils.java
./instrumentation/vertx-3.0/src/test/groovy/server/VertxWebServer.java
./instrumentation/vertx-reactive-3.5/src/test/groovy/VertxReactiveWebServer.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/A.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/B.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/C.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/D.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/E.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/F.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/G.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/Trace.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/TracedClass.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/tooling/bytebuddy/matcher/testclasses/UntracedClass.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/typed/client/SampleHttpClientTypedSpan.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/typed/client/SampleHttpClientTypedTracer.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/typed/server/SampleHttpServerTypedSpan.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/typed/server/SampleHttpServerTypedTracer.java
./javaagent-tooling/src/test/groovy/io/opentelemetry/javaagent/typed/TypedTracerDemonstration.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/AgentTestRunner.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/InMemoryExporter.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/utils/ClasspathUtils.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/utils/ExceptionUtils.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/utils/OkHttpUtils.java
./testing-common/src/main/groovy/io/opentelemetry/instrumentation/test/utils/PortUtils.java
```

### PR DESCRIPTION
**Pull request by trask**
Closes #1653

### CODE REVIEW

File: testing-common/src/main/java/io/opentelemetry/instrumentation/test/utils/ClasspathUtils.java [hunk 1]
```diff
@@ -126,7 +125,7 @@ public static ClassPath getTestClasspath() {
   }
 
   private static ClassPath computeTestClasspath() {
-    ClassLoader testClassLoader = AgentTestRunner.class.getClassLoader();
+    ClassLoader testClassLoader = ClasspathUtils.class.getClassLoader();
```
Comment (trask) [inline testing-common/src/main/java/io/opentelemetry/instrumentation/test/utils/ClasspathUtils.java:128]: classes under `test/java` can't have dependencies on classes under `test/groovy`

**Review by anuraaga — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]
