### PR TITLE
Remove LongAdder and ClassValue usages from instrumentation-api

### LINKED ISSUE #4533: Remove `LongAdder` and `ClassValue` usages from instrumentation-api
**Describe the bug**
Animalsniffer detected that these classes are not supported by Android API level 21 - they're used inside our own code in the `instrumentation-api` module.

**Steps to reproduce**
See #4505

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Resolves #4533

### CODE REVIEW

File: instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java [hunk 1]
```diff
@@ -100,44 +100,44 @@ private CounterNames() {}
 
   // this class is threadsafe.
   private static class KindCounters {
-    private final LongAdder server = new LongAdder();
-    private final LongAdder client = new LongAdder();
-    private final LongAdder internal = new LongAdder();
-    private final LongAdder consumer = new LongAdder();
-    private final LongAdder producer = new LongAdder();
+    private final AtomicLong server = new AtomicLong();
```
Comment (anuraaga) [inline instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java:103]: I think `LongAdder` is important in normal code. We should have a wrapper around the two types based on classpath check, and can use `@IgnoreJreRequirement` to allow LongAdder

Comment (trask) [reply instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java:103]: `AtomicLong` counters seem acceptable here since they are only used when agent debug is enabled. Not sure whether we'll need our own high-throughput counters in instrumentation, since typically that kind of work will be delegated to the Metrics API.

**Review by trask — APPROVED** [review]

File: instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java (hunk 1 above)
Comment (anuraaga) [reply instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java:103]: Ah thanks for pointing that out - agree if only when debug is enabled, AtomicLong is fine

**Review by anuraaga — APPROVED** [review]
