### PR TITLE
fix(instrumentation/jdbc): URL Parser StringIndexOutOfBoundsException fix

### LINKED ISSUE #14150: [BUG] StringIndexOutOfBoundsException when parsing MySQL Replication mode URL in JDBC instrumentation
### Describe the bug

When using the MySQL driver Replication mode, JDBC insert pile trying to parse the internal generated URL `**internally_generated**` because `dbLoc = -1` cause ` StringIndexOutOfBoundsException ` anomalies

### Steps to reproduce

I've created a complete reproduction case with: https://github.com/wl2027/otel-java-examples/tree/main/mysql-replication-demo

### Expected behavior

1. fix the exception (at present)
2. extract real host info (later)
Add instrumentation to MySQL driver to capture real host/port info. This can construct an accurate service topology diagram

### Actual behavior

- Stack Trace

```
[otel.javaagent 2025-06-27 17:50:00:042 +0800] [Druid-ConnectionPool-Create-866045247] DEBUG io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser - Error parsing URL
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1967)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser$6.doParse(JdbcConnectionUrlParser.java:355)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser$5.doParse(JdbcConnectionUrlParser.java:281)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser.parse(JdbcConnectionUrlParser.java:943)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcUtils.computeDbInfo(JdbcUtils.java:109)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcUtils.extractDbInfo(JdbcUtils.java:87)
    at io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.DbRequest.create(DbRequest.java:37)
```

- arthas
```
[arthas@1]$ watch io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser\$* doParse '{params,returnObj}' -x 3 -n 5
Press Q or Ctrl+C to abort.
Affect(class count: 20 , method count: 20) cost in 471 ms, listenerId: 1
method=io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser$6.doParse location=AtExceptionExit
ts=2025-06-27 22:38:46.523; [cost=0.043679ms] result=@ArrayList[
    @Object[][
        @String[**internally_generated**17489615264691**],
        @Builder[
            system=@String[mysql],
            subtype=null,
            shortUrl=null,
            user=null,
            name=null,
            db=@String[**internally_generated**17489615264619**],
            host=@String[localhost],
            port=@Integer[3306],
        ],
    ],
    null,
]
method=io.opentelemetry.javaagent.shaded.instrumentation.jdbc.internal.JdbcConnectionUrlParser$5.doParse location=AtExceptionExit
ts=2025-06-27 22:38:46.524; [cost=0.847149ms] result=@ArrayList[
    @Object[][
        @String[mysql:loadbalance://**internally_generated**1748961526469**],
        @Builder[
            system=@String[mysql],
            subtype=null,
            shortUrl=null,
            user=null,
            name=null,
            db=@String[**internally_generated**1748961526469**],
            host=@String[localhost],
            port=@Integer[3306],
        ],
    ],
    null,
]

```

### Javaagent or library instrumentation version

v2.17.0

### Environment

**JDK**: jdk8+
**OS**: macos

### Additional context

recurrence #2741

### PR DESCRIPTION
**Pull request by wl2027**
#14150

### CODE REVIEW

File: instrumentation/jdbc/library/src/test/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParserTest.java [hunk 1]
```diff
@@ -1374,4 +1377,16 @@ static Stream<Arguments> args(ParseTestArgument... testArguments) {
...
+
+  @ParameterizedTest
+  @ValueSource(
+      strings = {
+        "mysql:loadbalance://string_without_slash",
+        "mysql:loadbalance://host:3306", // with port but no slash
+        "mariadb:failover://[::1]:3306" // IPv6 without slash
+      })
+  void testMysqlUrlsWithoutSlashDoNotThrowException(String url) {
+    assertThatCode(() -> MYSQL.doParse(url, DEFAULT.toBuilder().system("mysql")))
```
Comment (laurit) [inline instrumentation/jdbc/library/src/test/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParserTest.java]: it is better to test the expected result for parsing as in `testMySqlParsing`

File: instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParser.java [hunk 2]
```diff
@@ -339,14 +339,14 @@ DbInfo.Builder doParse(String jdbcUrl, DbInfo.Builder builder) {
 
       if (portLoc > 0) {
         hostEndLoc = portLoc;
-        int portEndLoc = clusterSepLoc > 0 ? clusterSepLoc : dbLoc;
+        int portEndLoc = clusterSepLoc > 0 ? clusterSepLoc : (dbLoc > 0 ? dbLoc : jdbcUrl.length());
```
Comment (laurit) [inline instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParser.java]: I don't really like using the ternary operator twice on the same line. If `dbLoc` is `-1` then `builder.db(jdbcUrl.substring(dbLoc + 1));` a few lines up will set the db name to the content of jdbc url, that is also wrong.

Comment (weilhuang) [reply instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParser.java]: So should we set a default value for the database?  That doesn't seem quite right either.  To fully fix this issue, I think the solution is to instrument the MySQL driver separately to obtain the original JDBC URL.

Comment (laurit) [reply instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcConnectionUrlParser.java]: We could leave it unset.
